### ISSUE TITLE
Metadata info, like updated_at times, for content

### ISSUE THREAD

**Issue by LeticiaEsparza** [looker-open-source/gzr#10]
Had a customer interested in seeing metadata information while using gazr. Specifically, they wanted to see when dashboards were last updated. Suggested using the API to view `updated_at` details.

**Comment by seanlhiggins** [comment]
+1 
Would love to see which group_ids have access to a space. Should be feasible with the `content_metadata_id`from the GET /spaces/{space_id} and GET /content_metadata_access calls.

**Comment by michaelcramer** [comment]
Noted enhancement suggestion for potential addition to roadmap.
