### ISSUE TITLE
Not able to use gzr import command to create new looks.

### ISSUE THREAD

**Issue by chaitanyavarman** [looker-open-source/gzr#129]
Getting this error 👍 Error creating look({
  "title": "1.4.0 Top Categories",
  "description": "",
  "is_run_on_load": true,
  "deleted": false,
  "public": false,
  "slug": null,
  "query_id": "313306",
  "user_id": "799",
  "space_id": "1263"
})
The resource you're looking for could not be found

ERROR: The resource you're looking for could not be found

**Comment by chaitanyavarman** [comment]
BUt with same command modifying look we are able to do

**Comment by ddaugherty** [comment]
Hello

I ran a quick test using **"gzr look cat <look ID>"** to export a look to a JSON file and then used **"gzr import"** to import that JSON with no issues. 

When you mentioned you had success after “modifying look.” Are you referring to the JSON? 

You may want to test it with  --api_version 3.1 added as a parameter. 

Also, if possible, please reply with the individual steps you are using and maybe we can go from there.  Please make sure you are using the latest version of Gazer. 

Thanks.

**Comment by ddaugherty** [comment]
Hello @chaitanyavarman ,

Please let us know if this is still an issue.  If not, we plan on closing this ticket within 3 business days. Thank you.

**Comment by jannarobertson-bytecode** [comment]
@chaitanyavarman this issue will be closed; please open a new one if this is still unresolved after trying again with the recommendations.
