### ISSUE TITLE
gzr space export SPACE_ID command throwing error

### ISSUE THREAD

**Issue by ra185170** [looker-open-source/gzr#130]
The command **`gzr space export SPACE_ID`** is throwing the following error. The same command was working fine until the last Looker upgrade. Now suddenly we start seeing this error. We are unable to deploy Looks and Dashboards from dev to stag, prod

Looker version: **22.4.29**

**Error**: Traceback (most recent call last):
        18: from C:/Ruby26-x64/bin/gzr:23:in `<main>'
        17: from C:/Ruby26-x64/bin/gzr:23:in `load'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.44/exe/gzr:36:in `<top (required)>'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.44/lib/gzr/commands/space.rb:80:in `export'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:49:in `execute'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.44/lib/gzr/modules/session.rb:207:in `with_session'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:81:in `block in execute'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:87:in `process_space'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.44/lib/gzr/modules/space.rb:65:in `query_space'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/looker-sdk-0.0.7/lib/looker-sdk/client/dynamic.rb:105:in `method_missing': undefined method `space' for #<LookerSDK::Client:0x0000000005c687c0> (NoMethodError)

**Comment by AdamMinton** [comment]
Hi @ra185170,

Can you ensure that gzr has been updated to the latest version? In https://github.com/looker-open-source/gzr/releases/tag/v0.2.54 there was a "fix" to avoid using the api 4.0. It looks like you're using gazer-0.2.44 and not gazer-0.2.54

**Comment by sukhadj** [comment]
Hey @AdamMinton, do you have any docs that I can use to upgrade gazer to latest version. I am completely new to ruby and references at other places are overwhelming. 
Steps I had taken while installing old version - 
1. Installed rbenv
 `rbenv install 2.6.5`
2. `rbenv global 2.6.5`
3. `gem install gazer`

But when I check gzr --version it still points to older version. Am I missing anything?


Thanks in advance!

**Comment by jannarobertson-bytecode** [comment]
Hello @ra185170,

Checking back on this to see if upgrading to the latest version of gzr (0.2.54) has resolved the issue.  If we don't hear back within 3 business days, we will presume that this was resolved and close this issue.

**Comment by ra185170** [comment]
Hi @jannarobertson-bytecode 

Upgrading the gazer version resolved the issue. Issue can be closed.

Thank you!

**Comment by jannarobertson-bytecode** [comment]
Excellent, thanks @ra185170!
