### ISSUE TITLE
Error on `dashboard cat` with `--plans` option

### ISSUE THREAD

**Issue by jiepiao** [looker-open-source/gzr#131]
Getting errors on `dashboard cat` command with --plans option and I think this is because `query_scheduled_plans_for_dashboard` returns Array but dashboard cat expects a hash. Could you take a look?

https://github.com/looker-open-source/gzr/blob/eaa9b703211a9bf62daad1bba9fa99b572a586dc/lib/gzr/modules/dashboard.rb#L253

<img width="1424" alt="Screen Shot 2022-04-25 at 3 32 36 PM" src="https://user-images.githubusercontent.com/92333171/165185566-70b85632-612c-4f5c-bb31-91c4e1210cd3.png">

<img width="1430" alt="Screen Shot 2022-04-25 at 3 31 19 PM" src="https://user-images.githubusercontent.com/92333171/165185425-491aba28-f7d5-4257-8f15-9a520371cc80.png">

**Comment by ddaugherty** [comment]
Hello @jiepiao,

We are aware of the issue and will be proposing a fix.  

Thanks.
Daniel
