### ISSUE TITLE
[Feature Request] Subcommand to import Space from directory generated by export

### ISSUE THREAD

**Issue by jasondamour** [looker-open-source/gzr#132]
Hello,

The docs for `gzr space export` state:
> One interesting consequence of exporting a space into a directory tree is that you can then place its contents under version control using a tool like git. In this way user defined content changes can be tracked over time, and older versions of content can be restored if desired.

However, there seems to be no way to import that directory tree back into Looker. A command like `gzr space import [DIRECTORY] [ROOT_SPACE_ID]` would make sense to uptake that generated space tree back into looker.

**Comment by AdamMinton** [comment]
Hey @jasondamour,

Can I understand your use case a bit? Are you manipulating the folder directories locally or just migrating it from one instance to another?

We have a tool called [Looker Deployer](https://github.com/looker-open-source/looker_deployer) which handles the folder creation as it imports the content to the next instance. 

Thanks!

**Comment by jannarobertson-bytecode** [comment]
Hi @jasondamour,

Would you please be able to help us understand your use case, as per @AdamMinton's request above?

**Comment by jasondamour** [comment]
@jannarobertson-bytecode @AdamMinton our use case is to copy dashboards from one instance to another, storing a snapshot in git as we do. So the looker-deployer tool looks perfect. Issue can be closed, thank you
