### ISSUE TITLE
Dashboard import command failure with --force option after upgrading to 22.8

### ISSUE THREAD

**Issue by jiepiao** [looker-open-source/gzr#135]
Hi Team,

I am getting errors after the looker is upgraded to 22.8. Before this upgrade, we are able to force import the dashboard with gazer command.

Error message:
![Screen Shot 2022-05-17 at 12 11 56 PM](https://user-images.githubusercontent.com/92333171/168891832-7a3d76de-3ca0-41cd-8364-f78cf3e07422.png)

**Comment by ddaugherty** [comment]
@jiepiao 

No problem, I'm glad it worked out.  

Daniel
