### ISSUE TITLE
gem install gazer -v 0.2.54 fails

### ISSUE THREAD

**Issue by alec-flatiron** [looker-open-source/gzr#137]
Hi all, in a dockerfile we get gazer installed (v0.2.54) - today we started to get an error, which seems associated with a new release of the multipart-post package. 

We run
```
RUN apt update
RUN apt -y install ruby
RUN gem install gazer -v 0.2.54
```

This errors with: `Error installing gazer: The last version of multipart-post (~> 2) to support your Ruby & RubyGems was 2.2.0. Try installing it with `gem install multipart-post -v 2.2.0` and then running the current command again. multipart-post requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.`

I see in the Gemfile.lock there is an entry for `multipart-post (2.1.1)` - I don't know rails, so evidently that is not the version being installed. I don't know how that Gemfile.lock is invoked or why that dependency isn't the one that's loaded (maybe you can explain that for me).

In any case, running the suggested `gem install multipart-post -v 2.2.0` before the `gem install gazer ..` works, but it seems like it should be unnecssary.

**Comment by ddaugherty** [comment]
Hello. 

I not seeing the same issue when I try this, may I ask what base container you are using? 

Thanks. 
Daniel

**Comment by alec-flatiron** [comment]
Ah, we're using `python:3.7-slim-buster` which looks like it's debian based. I presume this is an us problem then so we can sort it out. Thanks for getting back to us though.
