### ISSUE TITLE
error while importing dashbords: resource already exists

### ISSUE THREAD

**Issue by swethadanda** [looker-open-source/gzr#14]
deleted the existing dashboard and tried to re-import dashboard from another instance. Its throwing an error resource already exists, even with --force parameter on the import 

The resource already exists.

/var/lib/gems/2.3.0/gems/looker-sdk-0.0.6/lib/looker-sdk/response/raise_error.rb:15:in `on_complete'
/var/lib/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
/var/lib/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
/var/lib/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/var/lib/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/var/lib/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/var/lib/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/var/lib/gems/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
/var/lib/gems/2.3.0/gems/looker-sdk-0.0.6/lib/looker-sdk/client.rb:280:in `request'
/var/lib/gems/2.3.0/gems/looker-sdk-0.0.6/lib/looker-sdk/client.rb:84:in `post'
/var/lib/gems/2.3.0/gems/looker-sdk-0.0.6/lib/looker-sdk/client/dynamic.rb:97:in `invoke_remote'
/var/lib/gems/2.3.0/gems/looker-sdk-0.0.6/lib/looker-sdk/client/dynamic.rb:63:in `method_missing'
/var/lib/gems/2.3.0/gems/gazer-0.2.6/lib/gzr/modules/dashboard.rb:59:in `create_dashboard'
/var/lib/gems/2.3.0/gems/gazer-0.2.6/lib/gzr/commands/dashboard/import.rb:92:in `sync_dashboard'
/var/lib/gems/2.3.0/gems/gazer-0.2.6/lib/gzr/commands/dashboard/import.rb:35:in `block (2 levels) in execute'
/var/lib/gems/2.3.0/gems/gazer-0.2.6/lib/gzr/modules/filehelper.rb:57:in `read_file'
/var/lib/gems/2.3.0/gems/gazer-0.2.6/lib/gzr/commands/dashboard/import.rb:33:in `block in execute'
/var/lib/gems/2.3.0/gems/gazer-0.2.6/lib/gzr/modules/session.rb:163:in `with_session'
/var/lib/gems/2.3.0/gems/gazer-0.2.6/lib/gzr/commands/dashboard/import.rb:29:in `execute'
/var/lib/gems/2.3.0/gems/gazer-0.2.6/lib/gzr/commands/dashboard.rb:37:in `import'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:115:in `invoke'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:238:in `block in subcommand'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/var/lib/gems/2.3.0/gems/gazer-0.2.6/exe/gzr:14:in `<top (required)>'
/usr/local/bin/gzr:22:in `load'
/usr/local/bin/gzr:22:in `<main>'

**Comment by timmcanty** [comment]
I am seeing the same issue, without ever deleting a dashboard.

**Comment by deangelo-llooker** [comment]
gzr has been paying attention to soft-deleted objects for a while now. Closing this issue.
