### ISSUE TITLE
Forecast settings on looks do not get imported

### ISSUE THREAD

**Issue by todoace** [looker-open-source/gzr#152]
Not sure if this is a Looker API issue or a gzr issue, but it's an issue.
When "gzr look cat"ing a look which has a Forecast configured the forecast metadata is in the output.
When "gzr look import"ing that look back in the forecast metadata is gone.

**Comment by jannarobertson-bytecode** [comment]
@todoace can you please confirm that this is still an issue after the most recent release and also the Gazer version you're using?

**Comment by jannarobertson-bytecode** [comment]
@todoace please reopen the issue and confirm the Gazer version you're using if you're able to replicate. Thanks!
