### ISSUE TITLE
Not able to import looks with --api_version 4.0 flag

### ISSUE THREAD

**Issue by vaibhavyadnik** [looker-open-source/gzr#155]
We are using api version 4.0. And I am not able to import looks with --api version 4.0 flag in the following command "$ gr look import Path/To/Look 123 My\
Look.json 123 --host foo.bar.mycompany.com --api version 4.0". Also it is not throwing any error or warning for this. If I do not add --api version 4.0 in command, then it imports looks with api 3.1. it is taking 3.1 api version by default.We are using latest gazer version which 0.2.56. Could you please help?

**Comment by ddaugherty** [comment]
Hello @vaibhavyadnik 

There is a PR in the pipelines that should help but the current version is locked to 3.1.   Hopefully they will be applied shortly.

Daniel

**Comment by vaibhavyadnik** [comment]
Thank you for sharing this information with me. If I may ask, could you please let me know what is the expected ETA for this?

**Comment by drstrangelooker** [comment]
The new version - 0.2.60 - is released. There is no need to use an `--api` flag now.
