### ISSUE TITLE
Gazer with Looker API 4.0

### ISSUE THREAD

**Issue by jiepiao** [looker-open-source/gzr#161]
Hi Team,

Looker API 3.1 will be officially disabled in June 2023 and the gzr command is depends on 3.1. Do you have any plan to upgrade to Looker API 4.0 or any suggestion how should we migrate the gazer to Looker API 4.0?

**Comment by drstrangelooker** [comment]
The latest version of gazer works with the 4.0 endpoint.

**Comment by drstrangelooker** [comment]
Sorry. I have the PR merged but haven't made the release yet.

**Comment by drstrangelooker** [comment]
I just released 2.59 which uses 4.0.

**Comment by drstrangelooker** [comment]
I'm sorry. I don't have any specific information for looker_deployer.

**Comment by gmarceau-flatiron** [comment]
Thanks for letting us know.
