### ISSUE TITLE
Unable to import new  UDD dashboards to another instance

### ISSUE THREAD

**Issue by JanChen22** [looker-open-source/gzr#164]
During importing new UDD dasboards to production instance, see this meesage:
 
/opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.59/lib/gzr/commands/dashboard/import.rb:97:in `block (3 levels) in execute': undefined method `first' for nil:NilClass (NoMethodError)
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.59/lib/gzr/commands/dashboard/import.rb:94:in `map'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.59/lib/gzr/commands/dashboard/import.rb:94:in `block (2 levels) in execute'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.59/lib/gzr/modules/filehelper.rb:88:in `read_file'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.59/lib/gzr/commands/dashboard/import.rb:54:in `block in execute'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.59/lib/gzr/modules/session.rb:249:in `with_session'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.59/lib/gzr/commands/dashboard/import.rb:50:in `execute'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.59/lib/gzr/commands/dashboard.rb:78:in `import'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/gazer-0.2.59/exe/gzr:36:in `<top (required)>'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/bin/gzr:23:in `load'
                from /opt/hostedtoolcache/Ruby/2.6.10/x64/bin/gzr:23:in `<main>'

**Comment by AdamMinton** [comment]
This is related to an issue in [gzr](https://github.com/looker-open-source/gzr/issues/166). Please do the following when installing gazer:

Change `gem install gazer` to `gem install gazer -v 0.2.58`. This will install the previous version of gzr and Looker Deployer will work successfully.

**Comment by JanChen22** [comment]
It worked now after the change you suggested.

Thanks
Jan

From: AdamMinton ***@***.***>
Sent: Monday, April 3, 2023 11:48 AM
To: looker-open-source/gzr ***@***.***>
Cc: Chen, Jan ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [looker-open-source/gzr] Unable to import new UDD dashboards to another instance (Issue #164)

CAUTION: This email was sent from an EXTERNAL source. Use caution when clicking links or opening attachments.
________________________________

This is related to an issue in gzr<https://urldefense.com/v3/__https:/github.com/looker-open-source/gzr/issues/166__;!!KMayzP4JbQ!Y1uWv4arnyZEKWT5DfeRD2oYhQipqhI2EuSkx3U6IoT_eg78PyGsdy_QmNHKRQRlMiE8zyiLjlte5_UxTdhiGwfpOw$>. Please do the following when installing gazer:

Change gem install gazer to gem install gazer -v 0.2.58. This will install the previous version of gzr and Looker Deployer will work successfully.

**Comment by drstrangelooker** [comment]
This should work now with 0.2.60.
