### ISSUE TITLE
Getting an error when migrating using Gazer & LookerDeployer

### ISSUE THREAD

**Issue by ramatejas** [looker-open-source/gzr#165]
Using Gazer V 0.2.54 (also tried with V0.2.59 & 0.2.58) and Looker_Deployer V0.3.9. Getting the following error started this week only:

/var/lib/gems/2.7.0/gems/looker-sdk-0.1.4/lib/looker-sdk/client.rb:475:in `merge_content_type_if_body': uninitialized constant Faraday::UploadIO (NameError)
	from /var/lib/gems/2.7.0/gems/looker-sdk-0.1.4/lib/looker-sdk/client/dynamic.rb:149:in `invoke_remote'
	from /var/lib/gems/2.7.0/gems/looker-sdk-0.1.4/lib/looker-sdk/client/dynamic.rb:107:in `method_missing'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/lib/gzr/modules/dashboard.rb:99:in `update_dashboard'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/lib/gzr/commands/dashboard/import.rb:168:in `sync_dashboard'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/lib/gzr/commands/dashboard/import.rb:66:in `block (2 levels) in execute'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/lib/gzr/modules/filehelper.rb:88:in `read_file'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/lib/gzr/commands/dashboard/import.rb:54:in `block in execute'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/lib/gzr/modules/session.rb:249:in `with_session'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/lib/gzr/commands/dashboard/import.rb:50:in `execute'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/lib/gzr/commands/dashboard.rb:78:in `import'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/exe/gzr:36:in `<top (required)>'
	from /usr/local/bin/gzr:[23](https://github.com/sharphealthcare/looker-clinical/actions/runs/4557253637/jobs/8083675952#step:4:24):in `load'
	from /usr/local/bin/gzr:23:in `<main>'
Modifying existing dashboard [35](https://github.com/sharphealthcare/looker-clinical/actions/runs/4557253637/jobs/8083675952#step:4:36) Emergency Department NDNQI Statistics in space 10

**Comment by shcsd-ctownsend** [comment]
We had to remove the older version of the faraday gem, roll back manually to looker-sdk 1.2 and then update the import.rb file with the following to correct the nil error:

`source_dashboard_layouts = data[:dashboard_layouts].map do |new_layout|
                layout_obj = nil
                if new_layout[:active]
                  if dashboard[:dashboard_layouts].nil? || dashboard[:dashboard_layouts].empty?
                  else
                    layout_obj = get_dashboard_layout(dashboard[:dashboard_layouts].first.id)
                    say_warning "Updating layout #{layout_obj.id}" if @options[:debug]
                  end
                else
                  layout = new_layout.select do |k,v|
                    (keys_to_keep('create_dashboard_layout') - [:dashboard_id]).include? k
                  end
                  layout[:dashboard_id] = dashboard.id
                  say_warning "Creating dashboard layout #{layout}" if @options[:debug]
                  layout_obj = create_dashboard_layout(layout)
                end
                unless layout_obj.nil?
                  layout_components = new_layout[:dashboard_layout_components].zip(layout_obj.dashboard_layout_components)
                  layout_components.each do |source,target|
                    component = keys_to_keep('update_dashboard_layout_component').collect do |e|
                      [e,nil]
                    end.to_h
                    component[:dashboard_layout_id] = target.dashboard_layout_id

                    component.merge!(source.select do |k,v|
                      (keys_to_keep('update_dashboard_layout_component') - [:id,:dashboard_layout_id]).include? k
                    end)

                    component[:dashboard_element_id] = elem_table.assoc(source[:dashboard_element_id])[1]
                    say_warning "Updating dashboard layout component #{target.id}" if @options[:debug]
                    update_dashboard_layout_component(target.id,component)
                  end
                end
                upsert_plans_for_dashboard(dashboard.id,@me.id,data[:scheduled_plans]) if data[:scheduled_plans]
                output.puts "Imported dashboard #{dashboard.id}" unless @options[:plain]
                output.puts dashboard.id if @options[:plain]
              end
            end
          end
        end`

**Comment by drstrangelooker** [comment]
This should work properly with 0.2.60.
