### ISSUE TITLE
The resources you're looking for could not be found

### ISSUE THREAD

**Issue by pranilshah04** [looker-open-source/gzr#174]
Hi. I am using gazer version 0.2.60 but getting this error when trying to import dashboards into the destination/Production looker environment:

The resource you're looking for could not be found

/var/lib/gems/2.7.0/gems/looker-sdk-0.1.4/lib/looker-sdk/response/raise_error.rb:37:in `on_complete'
/var/lib/gems/2.7.0/gems/faraday-1.10.3/lib/faraday/middleware.rb:19:in `block in call'
/var/lib/gems/2.7.0/gems/faraday-1.10.3/lib/faraday/response.rb:61:in `on_complete'
/var/lib/gems/2.7.0/gems/faraday-1.10.3/lib/faraday/middleware.rb:18:in `call'
/var/lib/gems/2.7.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:154:in `build_response'
/var/lib/gems/2.7.0/gems/faraday-1.10.3/lib/faraday/connection.rb:516:in `run_request'
/var/lib/gems/2.7.0/gems/faraday-1.10.3/lib/faraday/connection.rb:283:in `patch'
/var/lib/gems/2.7.0/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
/var/lib/gems/2.7.0/gems/looker-sdk-0.1.4/lib/looker-sdk/client.rb:316:in `request'
/var/lib/gems/2.7.0/gems/looker-sdk-0.1.4/lib/looker-sdk/client.rb:138:in `patch'
/var/lib/gems/2.7.0/gems/looker-sdk-0.1.4/lib/looker-sdk/client/dynamic.rb:149:in `invoke_remote'
/var/lib/gems/2.7.0/gems/looker-sdk-0.1.4/lib/looker-sdk/client/dynamic.rb:107:in `method_missing'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/lib/gzr/modules/dashboard.rb:100:in `update_dashboard'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/lib/gzr/commands/dashboard/import.rb:171:in `sync_dashboard'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/lib/gzr/commands/dashboard/import.rb:66:in `block (2 levels) in execute'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/lib/gzr/modules/filehelper.rb:88:in `read_file'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/lib/gzr/commands/dashboard/import.rb:54:in `block in execute'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/lib/gzr/modules/session.rb:244:in `with_session'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/lib/gzr/commands/dashboard/import.rb:50:in `execute'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/lib/gzr/commands/dashboard.rb:78:in `import'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/exe/gzr:36:in `<top (required)>'
/usr/local/bin/gzr:23:in `load'
/usr/local/bin/gzr:23:in `<main>'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/exe/gzr:36:in `<top (required)>'
/usr/local/bin/gzr:23:in `load'
/usr/local/bin/gzr:23:in `<main>'

Could you please suggest a solution? Thanks in advance.

**Comment by drstrangelooker** [comment]
Can you rerun the command with `--debug` added to the command line and send me the output?

**Comment by pranilshah04** [comment]
We already have added --debug in our script.
We have this python file which uses a loop to import all dashboards inside a folder to the production looker environment:
```
for f in *.json
do
  echo "${f%.json}"
  if [ ${f:0:4}  == "Look" ]
  then
   gzr look import "${f%.json}".json $DEST_FOLDER_ID --host $HOST --port $PORT --debug --force --no-verify-ssl
  else
      if [ ${f:0:9} == "Dashboard" ] 
      then
       gzr dashboard import "${f%.json}".json $DEST_FOLDER_ID --host $HOST --port $PORT --debug --force --no-verify-ssl
      fi
   fi
done
```

When we run this python file, it throws this error:
Error updating dashboard(411,{
  "description": "",
  "hidden": false,
  "query_timezone": null,
  "refresh_interval": null,
  "title": "Dashboard Name",
  "preferred_viewer": "dashboards-next",
  "alert_sync_with_dashboard_filter_enabled": false,
  "background_color": null,
  "crossfilter_enabled": false,
  "enable_viz_full_screen": true,
  "filters_bar_collapsed": false,
  "filters_location_top": true,
  "load_configuration": "cache_run",
  "lookml_link_id": null,
  "show_filters_bar": null,
  "show_title": null,
  "text_tile_text_color": null,
  "tile_background_color": null,
  "tile_text_color": null,
  "title_color": null,
  "deleted": false,
  "appearance": null
})
The resource you're looking for could not be found

/var/lib/gems/2.7.0/gems/looker-sdk-0.1.4/lib/looker-sdk/response/raise_error.rb:37:in `on_complete'
/var/lib/gems/2.7.0/gems/faraday-1.10.3/lib/faraday/middleware.rb:19:in `block in call'
/var/lib/gems/2.7.0/gems/faraday-1.10.3/lib/faraday/response.rb:61:in `on_complete'
/var/lib/gems/2.7.0/gems/faraday-1.10.3/lib/faraday/middleware.rb:18:in `call'
/var/lib/gems/2.7.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:154:in `build_response'
/var/lib/gems/2.7.0/gems/faraday-1.10.3/lib/faraday/connection.rb:516:in `run_request'
/var/lib/gems/2.7.0/gems/faraday-1.10.3/lib/faraday/connection.rb:283:in `patch'
/var/lib/gems/2.7.0/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
/var/lib/gems/2.7.0/gems/looker-sdk-0.1.4/lib/looker-sdk/client.rb:316:in `request'
/var/lib/gems/2.7.0/gems/looker-sdk-0.1.4/lib/looker-sdk/client.rb:138:in `patch'
/var/lib/gems/2.7.0/gems/looker-sdk-0.1.4/lib/looker-sdk/client/dynamic.rb:149:in `invoke_remote'
/var/lib/gems/2.7.0/gems/looker-sdk-0.1.4/lib/looker-sdk/client/dynamic.rb:107:in `method_missing'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/lib/gzr/modules/dashboard.rb:100:in `update_dashboard'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/lib/gzr/commands/dashboard/import.rb:171:in `sync_dashboard'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/lib/gzr/commands/dashboard/import.rb:66:in `block (2 levels) in execute'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/lib/gzr/modules/filehelper.rb:88:in `read_file'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/lib/gzr/commands/dashboard/import.rb:54:in `block in execute'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/lib/gzr/modules/session.rb:244:in `with_session'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/lib/gzr/commands/dashboard/import.rb:50:in `execute'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/lib/gzr/commands/dashboard.rb:78:in `import'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
/var/lib/gems/2.7.0/gems/gazer-0.2.60/exe/gzr:36:in `<top (required)>'
/usr/local/bin/gzr:23:in `load'
/usr/local/bin/gzr:23:in `<main>'

**Comment by drstrangelooker** [comment]
Gazer found a dashboard with the same title or slug in that space. It is dashboard 411. But when gazer tries to update it we get an error that it is not found. Is it possible that the account you are using doesn't have access to that dashboard?

**Comment by pranilshah04** [comment]
Ah! Yes, the account I was using did not have edit access to the dashboard in Production. I changed the access settings and gazer works well now. Thanks for looking into it @drstrangelooker  I really appreciate your prompt help.
