### ISSUE TITLE
Dashbords not moving from folder to folder on the same environment using gzr dashboard mv ....

### ISSUE THREAD

**Issue by SivanarayanaReddyTamalampudi** [looker-open-source/gzr#188]
[Staging_Move_Shared_Dashboard_in_Staging_93.log](https://github.com/looker-open-source/gzr/files/11391329/Staging_Move_Shared_Dashboard_in_Staging_93.log)

**Comment by drstrangelooker** [comment]
There is a dashboard with the same title already in that space. So you can't move it there.

```
Error summary:
  field: [:title, :space_id]
  code: already_exists
  message: Dashboard with this title already exists.
```
