### ISSUE TITLE
Unable to connect with v0.3.10

### ISSUE THREAD

**Issue by ogarza** [looker-open-source/gzr#218]
I'm trying to connect to a looker hosted instance and I keep getting:

ERROR: Connection Failed.
Did you specify the --no-ssl option for an ssl secured server?
You may need to use --port=443 in some cases as well

I have Ruby v3.0.2p107 installed on ubuntu 22.04 LTS
The version of the looker-sdk gem is 0.1.6

It seems no matter what, the host is set to 'localhost'
```
oscar@u-vm-2:~$ gzr user me host=https://myhostnamehere.cloud.looker.com/ --client-id=abc123 --client-secret=qbc123 --debug --port=443
{"debug"=>true, "host"=>"localhost", "port"=>"443", "ssl"=>true, "verify_ssl"=>true, "timeout"=>60, "force"=>false, "token_file"=>false, "client_id"=>"abc123", "client_secret"=>"abc123", "fields"=>"id,email,last_name,first_name,personal_folder_id,home_folder_id", "plain"=>false, "csv"=>false}
using options ["debug=>true", "host=>localhost", "port=>443", "ssl=>true", "verify_ssl=>true", "timeout=>60", "force=>false", "token_file=>false", "client_id=>abc123", "fields=>id,email,last_name,first_name,personal_folder_id,home_folder_id", "plain=>false", "csv=>false"]
logout
ERROR: Connection Failed.
Did you specify the --no-ssl option for an ssl secured server?
You may need to use --port=443 in some cases as well.
```

**Comment by ogarza** [comment]
oh wow, I forgot the -- before host... I get the same error though

**Comment by drstrangelooker** [comment]
`--host=myhostnamehere.cloud.looker.com`, no `https://../` parts.

Cheers.
Mike

**Comment by ogarza** [comment]
Actually, the issue was with the versions, removing the https:// from the hostname: 

I am able to connect with:
ruby v 3.1.2p20
looker-sdk v 0.1.2
gazer v 0.2.58

the same command fails with the newer versions

**Comment by drstrangelooker** [comment]
Can you send me the command and the response with the https removed so I can see?

Thanks.

**Comment by ogarza** [comment]
I apologize again... I removed the https:// part but forgot to add the -- again... 

It is working correctly in both machines.

Thank you so much

**Comment by drstrangelooker** [comment]
No problem. Glad everything is working.
