### ISSUE TITLE
SSL Certificate could not be verified

### ISSUE THREAD

**Issue by Rkohn123** [looker-open-source/gzr#222]
Hello everyone, I'm trying to connect to my gcp instance in gzr but it doesn't work.

After putting in my looker.ini
[prod] base_url=https://xxx.cloud.looker.com:443 client_id=yyy client_secret=zzz verify_ssl=True 

and executing the following code :

gzr user me --host https://xxx.cloud.looker.com/ --port 443

I obtain the error :

ERROR: Connection Failed.
Did you specify the --no-ssl option for an ssl secured server?
You may need to use --port=443 in some cases as well.

What can I do ?

**Comment by drstrangelooker** [comment]
Use `gzr user me --host xxx.cloud.looker.com --port 443` with gzr, or don't include `--host ...` at all to use `looker.ini`.

**Comment by Rkohn123** [comment]
It doesn't work anyway :/

**Comment by drstrangelooker** [comment]
Does it work if you specify everything on the command line? Delete the Looker.ini file and try that first. Send me the result.

**Comment by Rkohn123** [comment]
Yep, I tried to remove the looker.ini file

`gzr user me --host https://xxx.cloud.looker.com/ --port 443     `
>> 
ERROR: Connection Failed.
Did you specify the --no-ssl option for an ssl secured server?
You may need to use --port=443 in some cases as well.

**Comment by drstrangelooker** [comment]
try `gzr user me --host xxx.cloud.looker.com --port 443`

**Comment by Rkohn123** [comment]
it's interesting because I've tried with the classic url .cloud.looker.com and I get the same error, on the other hand we have another url for the same looker instance that works and I get another error. 

Error loading credentials from netrc file for https://yyy.fr:443/api/4.0/
ERROR: Invalid credentials

In my .netrc file I have 

machine https://yyy.com
login zzz
password aaa

the problem is that I connect on the Looker instane only with SSO

**Comment by Rkohn123** [comment]
We find the source of the problem, it was because of the SAML. So when we went in an other looker instance without the SAML authentification it worked.

**Comment by drstrangelooker** [comment]
Thanks for the update
