### ISSUE TITLE
space export only half-works

### ISSUE THREAD

**Issue by Rkohn123** [looker-open-source/gzr#226]
Hello everyone, 

When I run the code below 
`gzr space export 1 --host xxx --port=443 --dir .`

gazer recovers some dahsboards and folders but other folders and dashboards are not recovered, this is the error I get. 

`gzr space export 1 --host looker.dataauchan.fr --port=443 --dir .       
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gazer-0.3.10/lib/gzr/modules/filehelper.rb:61:in `mkdir': Not a directory @ dir_s_mkdir -`

It's written "Comparaison temporelle (Errno::ENOTDIR)"

if I translate in english it's "Time comparison (Errno::ENOTDIR)"

Thanks you,

**Comment by drstrangelooker** [comment]
Are you running this in Windows or a Unix style environment? Gazer only supports Linux, though it should work fine on macOS as well.

If you are trying to run this from Windows, you might install the Windows Subsystem for Linux (WSL) and try running from there.

**Comment by Rkohn123** [comment]
Apparently, after removing the ":" in the folder title "use case : test" => "use case test" it worked pretty well.

**Comment by drstrangelooker** [comment]
We only escape characters that are invalid in Unix file names for space names and object names. So this is windows specific. Thanks for figuring it out.
