### ISSUE TITLE
Error copying dashboards when exporting folder: `block in query_dashboard: undefined method row`

### ISSUE THREAD

**Issue by ps-rleemon** [looker-open-source/gzr#227]
I experienced an issue today where nearly all of our dashboards failed to update properly after receiving the below error. This error occurred when running this command in our shell script:
`gzr folder export ${source_folder_id} --host=${SOURCE_HOST} --dir ./${RELEASE_BRANCH}/${parent_folder_name} --client-id=${CLIENT_ID} --client-secret=${CLIENT_SECRET}`

It looks like it has something to do with the 1st filter on the dashboard having an issue:
```
/opt/hostedtoolcache/Ruby/3.0.0/x64/lib/ruby/gems/3.0.0/gems/gazer-0.3.11/lib/gzr/modules/dashboard.rb:33:in `block in query_dashboard': undefined method `row' for ***:id=>"8994", :dashboard_id=>"1333", :name=>"Date", :title=>"Date", :type=>"field_filter", :explore=>"test_explore", :dimension=>"test_explore.__date", :row=>0, :allow_multiple_values=>true, :required=>true, :ui_config=>***:type=>"advanced", :display=>"popover"***, :model=>"brand_monitor", :listens_to_filters=>[], :default_value=>"1 days", :field=>***:align=>"left", :can_filter=>true, :category=>"dimension", :default_filter_value=>nil, :description=>"", :enumerations=>nil, :field_group_label=>"  Date", :fill_style=>"range", :fiscal_month_offset=>0, :has_allowed_values=>false, :hidden=>false, :is_filter=>false, :is_numeric=>false, :label=>"Text Explore  Date", :label_from_parameter=>nil, :label_short=>" Date", :map_layer=>nil, :name=>"test_explore.__date", :strict_value_format=>false, :requires_refresh_on_sort=>false, :sortable=>true, :suggestions
```

Has anyone else run into this issue? We are running gazer `0.3.11`. Looks had no problem copying; it was just dashboards that were affected, it seems.

**Comment by drstrangelooker** [comment]
I think I can fix this quickly.

**Comment by drstrangelooker** [comment]
Please update to version 0.3.12 and try again.

**Comment by ps-rleemon** [comment]
@drstrangelooker Thanks a ton for the quick fix! I performed an initial copy of 1 dashboard and it worked. I am now performing a full test by copying all of our dashboards.
