### ISSUE TITLE
Gazer folder export command failing while exporting Dashboard

### ISSUE THREAD

**Issue by TechBright** [looker-open-source/gzr#230]
We are facing an issue with exporting looker folder. It is failing at exporting one of our dashboard. The dashboard in question has no problems while it was opened in looker.

Error:

C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/modules/dashboard.rb:33:in `block in query_dashboard': undefined method `row' for 
{:id=>"9923", :dashboard_id=>"1701", :name=>"Department", :title=>"Department", :type=>"field_filter", :explore=>"direct_bill_cash", :dimension=>".Department_Name", :row=>1, 
:allow_multiple_values=>true, :required=>false, :ui_config=>{:display=>"popover", :type=>"tag_list"}, :model=>"model", :listens_to_filters=>[], :default_value=>"", 
:field=>{:align=>"left", :can_filter=>true, :category=>"dimension", :default_filter_value=>nil, :description=>"", :enumerations=>nil, :field_group_label=>nil, :fill_style=>nil, 
:fiscal_month_offset=>0, :has_allowed_values=>false, :hidden=>false, :is_filter=>false, :is_numeric=>false, :label=>"Direct Bill Cash Department", :label_from_parameter=>nil, 
:label_short=>"Department", :map_layer=>nil, :name=>".Department_Name", :strict_value_format=>false, :requires_refresh_on_sort=>false, :sortable=>true, :suggestions=>nil, 
:tags=>[], :type=>"string", :user_attribute_filter_types=>["string", "advanced_filter_string"], :value_format=>nil, :view=>"", :view_label=>"Direct Bill Cash", 
:dynamic=>false, :week_start_day=>"monday", :original_view=>"", :dimension_group=>nil, :error=>nil, :field_group_variant=>"Department", :measure=>false, :parameter=>false, 
:primary_key=>false, :project_name=>"project", :scope=>"", :suggest_dimension=>".Department_Name", :suggest_explore=>"direct_bill_cash", :suggestable=>true, 
:is_fiscal=>false, :is_timeframe=>false, :can_time_filter=>false, :time_interval=>nil, :lookml_link=>"/project/views/Module/Test.view.lkml?line=430", 
:permanent=>nil, :source_file=>"views/Module/Test.view.lkml", :source_file_path=>"project/views/Module/Test.view.lkml", :sql=>"${TABLE}.Department ", 
:sql_case=>nil, :filters=>nil, :times_used=>0}, :can=>{:create=>true, :update=>true, :destroy=>true, :index=>true, :show=>true, :show_errors=>true, :find_and_replace=>true}}:Hash (NoMethodError)

        data[:dashboard_filters]&.sort! { |a,b| a.row <=> b.row }
                                                 ^^^^
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/modules/dashboard.rb:33:in `sort!'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/modules/dashboard.rb:33:in `query_dashboard'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/modules/dashboard.rb:282:in `cat_dashboard'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/commands/folder/export.rb:108:in `block in process_folder'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/commands/folder/export.rb:107:in `each'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/commands/folder/export.rb:107:in `process_folder'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/commands/folder/export.rb:116:in `block in process_folder'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/commands/folder/export.rb:115:in `each'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/commands/folder/export.rb:115:in `process_folder'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/commands/folder/export.rb:116:in `block in process_folder'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/commands/folder/export.rb:115:in `each'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/commands/folder/export.rb:115:in `process_folder'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/commands/folder/export.rb:77:in `block in execute'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/modules/session.rb:306:in `with_session'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/commands/folder/export.rb:51:in `execute'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/lib/gzr/commands/folder.rb:84:in `export'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from C:/Users/<user>/.local/share/gem/ruby/3.2.0/gems/gazer-0.3.11/exe/gzr:36:in `<top (required)>'
        from C:/Ruby32-x64/bin/gzr:32:in `load'
        from C:/Ruby32-x64/bin/gzr:32:in `<main>'

Version:

ruby 3.2.2
gem 3.4.0
looker_sdk 0.1.6
gazer 0.3.11

command:
gzr folder export 117 --zip=test --host=xxxx --client-id=xxxx --client-secret=xxxx --port 443

Appreciate your response on this.

**Comment by drstrangelooker** [comment]
This is already fixed in 0.3.12. Just upgrade to the latest.

**Comment by TechBright** [comment]
Thank you very much. It worked after updating to suggested version. Much appreciated.
