### ISSUE TITLE
Can't export/import dashboard with merge_query

### ISSUE THREAD

**Issue by cphamIO** [looker-open-source/gzr#233]
I am using gazer version v0.3.12 and have two separate instances.  When trying to export folder with a dashboard that contains merge_query, I get resource not found. I then used Looker API explorer get dashboard method to dump code, then tried to import using gazer, I get the same resource not found error:

gzr folder export 101 $GZR_DEV
Error querying merge_query(6kkNO8mtdxYKiUZSfZEJra)
GET https://<MYCOMPANY>.looker.com/api/4.0/merge_queries/6kkNO8mtdxYKiUZSfZEJra: 404 - The resource you're looking for could not be found

I opened a support case with Looker and it's not an issue in Looker api. Their process is using LookML Dashboard method to export and import between projects/instance.

Has anyone come access issues with exporting/importing dashboard with merge_query?

**Comment by drstrangelooker** [comment]
There has been work recently in this area. Can you retry?

**Comment by cphamIO** [comment]
I just tried the export operation on version `v0.3.16` and it is resolved. I will try the import operation in upcoming days and report back. I would expect it to work as well.

**Comment by cphamIO** [comment]
Hi, something seem to have changed since I verified it worked. 
I'm getting the error again. But in Looker API Explorer on Looker portal `GET Merge Query` method works fine.

Command line result with gzr version v0.3.16

```
gzr folder export 448 $GZR_DEV --dir=/tmp  --timeout=100000
Error querying merge_query(0mt4IVDSV5aVU1M7l9rTZF)
GET https://iovationdev.looker.com/api/4.0/merge_queries/0mt4IVDSV5aVU1M7l9rTZF: 404 - { "message": "The resource you're looking for could not be found" }
```
