### ISSUE TITLE
I start Command Prompt with Ruby in Windows and get this error "certificate verify failed"

### ISSUE THREAD

**Issue by jondu2022** [looker-open-source/gzr#235]
Please see the error, please advise of the fix

C:/Ruby31-x64/lib/ruby/3.1.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=13.224.181.67:443 state=error: certificate verify failed (self signed certificate in certificate chain) (Faraday::SSLError)
        from C:/Ruby31-x64/lib/ruby/3.1.0/net/protocol.rb:46:in `ssl_socket_connect'
        from C:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:1048:in `connect'
        from C:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
        from C:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:965:in `start'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:112:in `request_with_wrapped_block'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:102:in `perform_request'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:66:in `block in call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/adapter.rb:45:in `connection'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:65:in `call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/request/url_encoded.rb:25:in `call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/rack_builder.rb:153:in `build_response'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/connection.rb:444:in `run_request'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/connection.rb:200:in `get'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/error.rb:108:in `error_docs'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/error.rb:89:in `error_doc_url'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/error.rb:201:in `build_error_message'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/error.rb:62:in `initialize'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/error.rb:56:in `new'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/error.rb:56:in `from_response'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/response/raise_error.rb:36:in `on_complete'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/middleware.rb:18:in `block in call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/response.rb:42:in `on_complete'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/middleware.rb:17:in `call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/rack_builder.rb:153:in `build_response'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/connection.rb:444:in `run_request'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/connection.rb:200:in `get'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/client.rb:316:in `request'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/client.rb:99:in `get'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/client/dynamic.rb:146:in `invoke_remote'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/client/dynamic.rb:107:in `method_missing'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:178:in `color_collection'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:237:in `rewrite_color_palette!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/modules/look.rb:197:in `block (2 levels) in cat_look'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:211:in `find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `block in find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `block in find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `block in find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `block in find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `block in find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `block in find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/modules/look.rb:196:in `block in cat_look'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:193:in `find_vis_config_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:195:in `block in find_vis_config_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:195:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:195:in `find_vis_config_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:195:in `block in find_vis_config_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:195:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:195:in `find_vis_config_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/modules/look.rb:195:in `cat_look'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/commands/folder/export.rb:101:in `block in process_folder'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/commands/folder/export.rb:100:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/commands/folder/export.rb:100:in `process_folder'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/commands/folder/export.rb:77:in `block in execute'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/modules/session.rb:306:in `with_session'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/commands/folder/export.rb:51:in `execute'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/commands/folder.rb:84:in `export'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/exe/gzr:36:in `<top (required)>'
        from C:/Ruby31-x64/bin/gzr:32:in `load'
        from C:/Ruby31-x64/bin/gzr:32:in `<main>'
C:/Ruby31-x64/lib/ruby/3.1.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=13.224.181.67:443 state=error: certificate verify failed (self signed certificate in certificate chain) (OpenSSL::SSL::SSLError)
        from C:/Ruby31-x64/lib/ruby/3.1.0/net/protocol.rb:46:in `ssl_socket_connect'
        from C:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:1048:in `connect'
        from C:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
        from C:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:965:in `start'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:112:in `request_with_wrapped_block'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:102:in `perform_request'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:66:in `block in call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/adapter.rb:45:in `connection'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:65:in `call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/request/url_encoded.rb:25:in `call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/rack_builder.rb:153:in `build_response'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/connection.rb:444:in `run_request'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/connection.rb:200:in `get'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/error.rb:108:in `error_docs'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/error.rb:89:in `error_doc_url'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/error.rb:201:in `build_error_message'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/error.rb:62:in `initialize'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/error.rb:56:in `new'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/error.rb:56:in `from_response'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/response/raise_error.rb:36:in `on_complete'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/middleware.rb:18:in `block in call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/response.rb:42:in `on_complete'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/middleware.rb:17:in `call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/rack_builder.rb:153:in `build_response'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/connection.rb:444:in `run_request'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.7.10/lib/faraday/connection.rb:200:in `get'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/client.rb:316:in `request'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/client.rb:99:in `get'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/client/dynamic.rb:146:in `invoke_remote'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/looker-sdk-0.1.6/lib/looker-sdk/client/dynamic.rb:107:in `method_missing'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:178:in `color_collection'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:237:in `rewrite_color_palette!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/modules/look.rb:197:in `block (2 levels) in cat_look'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:211:in `find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `block in find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `block in find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `block in find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `block in find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `block in find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `block in find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:213:in `find_color_palette_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/modules/look.rb:196:in `block in cat_look'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:193:in `find_vis_config_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:195:in `block in find_vis_config_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:195:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:195:in `find_vis_config_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:195:in `block in find_vis_config_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:195:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/command.rb:195:in `find_vis_config_reference'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/modules/look.rb:195:in `cat_look'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/commands/folder/export.rb:101:in `block in process_folder'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/commands/folder/export.rb:100:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/commands/folder/export.rb:100:in `process_folder'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/commands/folder/export.rb:77:in `block in execute'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/modules/session.rb:306:in `with_session'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/commands/folder/export.rb:51:in `execute'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/lib/gzr/commands/folder.rb:84:in `export'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/gazer-0.3.10/exe/gzr:36:in `<top (required)>'
        from C:/Ruby31-x64/bin/gzr:32:in `load'
        from C:/Ruby31-x64/bin/gzr:32:in `<main>'

**Comment by drstrangelooker** [comment]
Gazer is not supported on Windows. It is only tested with Linux, though we
have never had any issues with MacOS.

You can try the `--no-verify-ssl` flag. That might work.

If that does not work, Windows offers a feature called "Windows Subsystem
for Linux" or WSL for short. With WSL you can install a Linux system within
windows that you can use for Gazer.

I hope this helps.

Mike

**Comment by jondu2022** [comment]
We have NetSkope installed, 
By disabling it, we can use it without issue
