### ISSUE TITLE
SSL issue despite having no-verify-ssl

### ISSUE THREAD

**Issue by marawanaboelwafa** [looker-open-source/gzr#238]
**gzr look import 7073.json 913 --host=(host)  --port=19999 --debug --force --no-verify-ssl --client_id=(id) --client_secret=secret**

options: {"debug"=>true, "host"=>"my_host", "port"=>"19999", "ssl"=>true, "verify_ssl"=>false, "timeout"=>60, "force"=>true, "token_file"=>false, "client_id"=>"id", "client_secret"=>"secret"}
using options ["debug=>true", "host=>host", "port=>19999", "ssl=>true", "verify_ssl=>false", "timeout=>60", "force=>true", "token_file=>false", "client_id=>id"]
API current_version 4.0
Supported API versions ["4.0"]
connecting to ["api_endpoint=>https://host.com:19999/api/4.0", "connection_options=>{:ssl=>{:verify=>false, :verify_mode=>0}, :request=>{:timeout=>60}}", "user_agent=>Gazer 0.3.13", "client_id=>id", "client_secret=>*********"]
check for connectivity: true
verify authentication: true
logout
Traceback (most recent call last):
	16: from /usr/local/lib/ruby/gems/2.5.0/gems/gzr-0.3.13/exe/gzr:36:in `<main>'
	15: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/gzr-0.3.13/lib/gzr/commands/look.rb:74:in `import'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/gzr-0.3.13/lib/gzr/commands/look/import.rb:47:in `execute'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/gzr-0.3.13/lib/gzr/modules/session.rb:306:in `with_session'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/gzr-0.3.13/lib/gzr/commands/look/import.rb:51:in `block in execute'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/gzr-0.3.13/lib/gzr/modules/filehelper.rb:83:in `read_file'
	 1: from /usr/local/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/usr/local/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at 'ERROR: SSL Certificate could not be verified (JSON::ParserError)
Do you need the --no-verify-ssl option or the --no-ssl option?
'

**Comment by marawanaboelwafa** [comment]
i've tried using different gzr versions, nothing is working.

**Comment by drstrangelooker** [comment]
I'm looking into it. Did this just start? Have you been able to connect with gazer in the past?

**Comment by marawanaboelwafa** [comment]
this just started, I have used and connected gazer so many times previously.

**Comment by marawanaboelwafa** [comment]
hey @drstrangelooker any update?

**Comment by drstrangelooker** [comment]
Can you try upgrading ruby to a new version? That may resolve this.

**Comment by marawanaboelwafa** [comment]
Traceback (most recent call last):
	17: from /usr/local/lib/ruby/gems/2.5.0/gems/gzr-0.3.13/exe/gzr:36:in `<main>'
	16: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.3.1/lib/thor/base.rb:584:in `start'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.3.1/lib/thor.rb:338:in `block in subcommand'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.3.1/lib/thor/invocation.rb:116:in `invoke'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/gzr-0.3.13/lib/gzr/commands/look.rb:74:in `import'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/gzr-0.3.13/lib/gzr/commands/look/import.rb:47:in `execute'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/gzr-0.3.13/lib/gzr/modules/session.rb:305:in `with_session'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/gzr-0.3.13/lib/gzr/modules/session.rb:190:in `login'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/sawyer-0.6.0/lib/sawyer/agent.rb:107:in `call'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/sawyer-0.6.0/lib/sawyer/agent.rb:107:in `new'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/looker-sdk-0.0.5/lib/looker-sdk/sawyer_patch.rb:16:in `initialize'
/usr/local/lib/ruby/gems/2.7.0/gems/sawyer-0.6.0/lib/sawyer/response.rb:43:in `process_rels': undefined method `[]' for nil:NilClass (NoMethodError)

**Comment by marawanaboelwafa** [comment]
Upgraded ruby, installed necessary gems and now face this error.. can you please help? @drstrangelooker

**Comment by drstrangelooker** [comment]
I'm still trying to analyze this. Thanks for your patience.

**Comment by marawanaboelwafa** [comment]
updated ruby on the importing hosts as well as the exporting and it worked.

**Comment by drstrangelooker** [comment]
Thanks for the update
