### ISSUE TITLE
Dashboard Import Fails When Text Elements are Deleted And Replaced

### ISSUE THREAD

**Issue by timmcanty** [looker-open-source/gzr#24]
When using dashboard import across two Looker instances, the dashboard import will fail when a text element is destroyed and recreated. 

Repro:

1. In first Looker instance (A) on a fresh dashboard, create a text element 
2. In the same dashboard, create a tile from an explore.
3. Use Gazer to export/import the dashboard into Looker instance (B)
4. In A, on the same dashboard that was deployed, delete the text element.
5. In the same dashboard, recreate the text element with the *exact same copy* as the deleted element.
6. Attempt to use Gazer to export/import the dashboard into B

Expected:
The import is successful

Result:
Import fails with a message similar to `Cannot update text element with result_maker_id`

**Comment by deangelo-llooker** [comment]
I just pushed gazer version 0.2.19. I believe that will fix this issue. If it does not fix we can reopen.
