### ISSUE TITLE
Dashboard import command works in CLI but not in shell script

### ISSUE THREAD

**Issue by vikrampadwal1993** [looker-open-source/gzr#242]
I have written a shell script which exports dashboard, transforms it and import the transformed dashboard into new folder. Everything is working as expected except import.
 I am getting 404 error- The resource you're looking for could not be found. Suprisingly, when I execute the same command from CLI, it works without any issue.

**Comment by drstrangelooker** [comment]
That is odd. Can you share the shell script?

**Comment by vikrampadwal1993** [comment]
[
[dashboard_migration.txt](https://github.com/looker-open-source/gzr/files/14646809/dashboard_migration.txt)
](url)
PFA the script

**Comment by drstrangelooker** [comment]
It looks like there is already a dashboard with the name "Baseline EDD GMLOS Model Performance" in the destination folder, so the update isn't working. If you rename that dash it should work.
