### ISSUE TITLE
Failing to install gzr on action - "console" from wisper conflicts with installed executable from fastlane

### ISSUE THREAD

**Issue by laura-nmdp** [looker-open-source/gzr#245]
Long running action started failing last night on gzr install with the following error against the console with conflights:

Run sudo gem install gazer
  sudo gem install gazer
  shell: /bin/bash -e {0}
  
ERROR:  Error installing gazer:
	"console" from wisper conflicts with installed executable from fastlane
Successfully installed tty-tree-0.4.0
Successfully installed unicode_utils-1.4.0
Successfully installed strings-ansi-0.[2](https://github.com/bethematch/looker_content_sync/actions/runs/8648469851/job/23712340196#step:5:2).0
Successfully installed strings-0.2.1
Successfully installed tty-color-0.6.0
Successfully installed pastel-0.8.0
Successfully installed tty-table-0.12.0
Error: Process completed with exit code 1.

Please advise if any more information is needed - we use this to sync dashboards between two looker envs.

**Comment by mbclawson** [comment]
We're seeing the same error as well using: `sudo gem install gazer`.  A temp workaround has been to use `sudo gem install gazer --force` however we're not sure what's causing this/what a fix might be.

**Comment by laura-nmdp** [comment]
that did the trick to fix the install issue I was seeing, and we were able to run the action successfully with the `--force` added
I am going to keep this open until this is resolved by the bigger-up's within gazer/looker and we are able to remove the `--force`

**Comment by drstrangelooker** [comment]
Unfortunately there is nothing I can do about this. Both the whisper and fastlane gems want to install an executable named `console`. I don't control either of them.

You can uninstall the fastlane gem, or you can the rbenv utility to create separate standalone environments to run gazer.
