### ISSUE TITLE
Gazer failing to install Ubuntu

### ISSUE THREAD

**Issue by timrcase** [looker-open-source/gzr#246]
We use GitHub Actions to deploy content from our lower environment to production. We have been using the same workflow mostly without issue, apart from needing to upgrade the `looker-deployer` and/or `gazer` packages here and there, for a couple of years now but it suddenly stopped working 2 weeks ago with the following error:

```
ERROR:  Error installing gazer:
	"console" from wisper conflicts with installed executable from fastlane
```

We were using Gazer v0.3.13 at the time so I tried upgrading to v0.3.14 in hopes of resolving the issue but we got the same error. We use the `ubuntu-latest` runner (which is `ubuntu-22.04`) so I also tried downgrading to the `ubuntu-20.04` runner with the same results. Is anyone else running into this issue?

**Comment by laura-nmdp** [comment]
RE: See issue 245 here - https://github.com/looker-open-source/gzr/issues/245

I was told that this wasn't a looker issue, and to add `sudo gem install gazer --force` instead of `sudo gem install gazer`

hope this helps.

**Comment by timrcase** [comment]
Duplicate of #245
