### ISSUE TITLE
Ruby version and Gazer version is failed by extremely managed environments

### ISSUE THREAD

**Issue by karanmenthula** [looker-open-source/gzr#251]
I am running into an issue when using ruby version 2.7 and gazer version 3.1.6, unable to run the jobs with current version of python libraries . I wanted to install the latest version of Ruby and Gazer in Docker and looking for assistance here.

![Screenshot 2024-06-25 at 2 28 05 PM](https://github.com/looker-open-source/gzr/assets/171044970/3dfee1f9-2405-4666-8a0d-9e0c54f6a07c)

**Comment by drstrangelooker** [comment]
Can you try to use a later version of Ruby, 3.0 or later?
