### ISSUE TITLE
Can't export dashboard with merge_query

### ISSUE THREAD

**Issue by bmo992** [looker-open-source/gzr#260]
I am using gazer version v0.3.17. When trying to export a dashboard that contains merge_query, I get the following error message:
 
<img width="1440" alt="Capture d’écran 2024-08-06 à 14 08 58" src="https://github.com/user-attachments/assets/def9f8aa-85aa-4734-baa1-fe3ece91585e">

Error querying search_alerts(***
  "group_by": "dashboard",
  "fields": "id,dashboard_element_id",
  "all_owners": true,
  "limit": 64
***)

GET https://****.cloud.looker.com/api/4.0/alerts/search?all_owners=true&fields=id%2Cdashboard_element_id&group_by=dashboard&limit=64: 403 - You do not have access.

 // See: https://cloud.google.com/looker/docs/r/err/4.0/403/get/alerts/search

 // And: https://marketplace-api.looker.com/errorcodes/403.md

Must be an admin user to look up all alerts

Parameters used (for internal record)
![Uploading Capture d’écran 2024-08-06 à 14.09.10.png…]()

**Comment by drstrangelooker** [comment]
It isn't "exactly" a problem with `gzr`. What is happening is that `gzr` is outputting some warning text, but your python program is expecting just a json document.

I'm working on a fix that will write all the warning and error text to stderr instead of stdout. That should alleviate this.
