### ISSUE TITLE
Manage profiles

### ISSUE THREAD

**Issue by drstrangelooker** [looker-open-source/gzr#3]
Allow a user to specify `--profile=dev` instead of `--host=dev.looker.example.com` and store the auth key instead of re-logging in each time.

Info would be stored in a file like this...
```json
[
  {
    "profile":"dev",
    "host": "dev.looker.example.com",
    "port": "19999",
    "client_id": "XYZ",
    "client_secret": "123",
    "api_version": "3.1",
    "ssl": true,
    "verify_ssl": true,
    "token": "kahdskfhasdlkfnakls dnfkasd",
    "su_tokens": [
      {
        "user_id": 123,
        "token": "adnfkjashdfkjhaskjdbnfkasd"
      },
      {
        "user_id": 456,
        "token": "adnfkjashdfkjhaskjdbnfkasd"
      }
    ]
  },
  {
    "profile":"qa",
    "host": "qa.looker.example.com",
    "client_id": "XYZ",
    "client_secret": "123",
    "token": "kahdskfhasdlkfnakls dnfkasd"
  },
  {
    "profile":"prod",
    "host": "prod.looker.example.com",
    "client_id": "XYZ",
    "client_secret": "123",
    "token": "kahdskfhasdlkfnakls dnfkasd"
  }
]
```

The file would be searched for in a location optionally specified by the user, then the local dir, then each parent dir, then in the user's root dir.

The file must be permissioned as `rw-------`

The user would use `gzr login --profile=dev` to log in and save the token. A command like `gzr logout --profile=dev` would log out the token.

`gzr login --profile=dev --su=123` would set the su token. `gzr logout --profile=dev --su=123` would logout and delete the token.

`-p dev:123` would be short for `--profile=dev --su=123`

Before any command, gzr would verify that the authorization was still good. If not it would reauthorized and save the new token.

It is possible for multiple gzr processes to use the same file, so we want to have some sort of locking.

**Comment by deangelo-llooker** [comment]
@jax

**Comment by deangelo-llooker** [comment]
@josephaxisa

**Comment by michaelcramer** [comment]
Noted enhancement suggestion for potential addition to roadmap.
