### ISSUE TITLE
Space tree does not escape forward slash "/" character

### ISSUE THREAD

**Issue by pioneer903** [looker-open-source/gzr#32]
Space titles that contain a forward slash "/" do not properly show up using `space tree` command. 
Example: Space name "Test / Migration" would output just "Migration" ignoring whatever came before the slash. 
Back slash works fine. 

Thank you

**Comment by ryandunlavy** [comment]
It looks like this "/" stripping is built into the [tty-tree](https://github.com/piotrmurach/tty-tree) gem we use. I'm not seeing a way to adjust that natively.

**Comment by deangelo-llooker** [comment]
Should be fixed now. Please reopen if not fixed.
