### ISSUE TITLE
Feature Request: Space Import

### ISSUE THREAD

**Issue by ajcrutch** [looker-open-source/gzr#35]
I'd like to import an entire space all at once.  Basically, a list of json files (looks and dashboards) into one destination space.

**Comment by ajcrutch** [comment]
Cool idea, @ajcrutch! While you wait, here is some code which you can use to accomplish the same task.  
1) Edit the "Update me" parts
2) Save as a shell script in the same folder into which your json files were exported
3) Be sure to run chmod +x gzr_import.sh to make this executable
4) Run using ./gzr_import.sh
5) Marvel at all the colorful messages of success

```
#!/bin/bash

# Be sure to run chmod +x gzr_import.sh to make this executable
# run using ./gzr_import.sh

DEST_SPACE_ID=127        # UPDATE ME
HOST=local.looker.com     # UPDATE ME
PORT=19999                  # UPDATE ME

# Loop imports all the looks and dashboards in the current folder to the destination space as indicated above

for f in *.json
do
  echo "${f%.json}"
  if [ ${f:0:4}  == "Look" ]
  then
   gzr look import "${f%.json}".json $DEST_SPACE_ID --host $HOST --port $PORT --debug --force --no-verify-ssl
  else
      if [ ${f:0:9} == "Dashboard" ] 
      then
       gzr dashboard import "${f%.json}".json $DEST_SPACE_ID --host $HOST --port $PORT --debug --force --no-verify-ssl
      fi
   fi
done
```

You might need to add `--client_id=xxxx --client_secret=yyyy` after --no-verify-ssl if you haven't set up your .netrc file (see getting started page)

**Comment by ajcrutch** [comment]
> Cool idea, @ajcrutch! While you wait, here is some code which you can use to accomplish the same task.
Wow, thanks!

**Comment by Monte9** [comment]
@ajcrutch this is exactly what I was looking for, and it worked great! Thanks a lot. 💯

**Comment by sabarber-looker** [comment]
Hmm...so extending this concept, if we wanted to import a full export, which could contain nested spaces, we'd need to iterate over the folder structure and, if needed, create the child spaces in the right parent/child relationship and THEN execute this script, yes?

**Comment by drewgillson** [comment]
See https://github.com/llooker/looker_deployer for a solution

**Comment by michaelcramer** [comment]
Noted enhancement suggestion for potential addition to roadmap.
