### ISSUE TITLE
Space Export fails on too long name

### ISSUE THREAD

**Issue by JakubDvorakFD** [looker-open-source/gzr#37]
Hi,
When I run space export command I get this error if space contains look with a very long name: `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/package/tar_writer.rb:336:in 'split_name': File "Shared/really long file name.json" has a too long name (should be 100 or less) `

**Comment by deangelo-llooker** [comment]
This issue dependent on the feature request here... https://github.com/rubygems/rubygems/issues/1376

I'll spend some time thinking about how I can fix.

**Comment by deangelo-llooker** [comment]
I added an option `--zip` to use a zip file instead of a tar or tgz file. This should be a workaround for the problem. There isn't much I can do to make the tar or tgz work since the underlying code isn't there.
