### ISSUE TITLE
Issue when modifying dashboard including text tile

### ISSUE THREAD

**Issue by sampitcher** [looker-open-source/gzr#40]
Gazer version = v0.2.14
Looker version = 6.16.10

We have a customer set up on 2 instances, dev and prod. We are modifying content in dev instance, then promoting content to prod when changes have been made using gzr. We need to keep the dashboard slugs from dev to prod the same so links do not break..
The majority of dashboards move over fine, however if a dashboard contains a text tile we get this error message:

```gzr dashboard import ecommerce.json 9 --host=dysonsandbox.eu.looker.com --force
Modifying existing dashboard 2 E-commerce | Direct control tower in space 9
Error updating dashboard_element(27,{
  "body_text": "<p><a href=\"https://analytics.google.com/analytics/web/#/report/visitors-geo/a7823531w161529192p162626565/geo-segmentExplorer.segmentId=analytics.city&geo-table.plotKeys=%5B%5D/\" target=\"_blank\"><img src=\"https://s3-us-west-2.amazonaws.com/s.cdpn.io/1615306/Google%20Analytics%20logo_lockup_analytics_icon_vertical_black_2x.png\" alt=\"\" height=\"85\" /></a></p>",
  "dashboard_id": 2,
  "look_id": null,
  "merge_result_id": null,
  "note_display": null,
  "note_state": null,
  "note_text": null,
  "query_id": null,
  "refresh_interval": null,
  "result_maker": null,
  "subtitle_text": "",
  "title": "GA Icon",
  "title_hidden": false,
  "title_text": "",
  "type": "text"
})
Validation Failed
{:field=>"type", :code=>"invalid", :message=>"Result Maker IDs should not be provided for text elements", :documentation_url=>"http://docs.looker.com/"}```

So far I have to remove the text tile in dev content and then add it in manually in prod.

Thank you!

**Comment by HPNoha** [comment]
Same here, on version 6.14

**Comment by mjassows** [comment]
Also seeing this on 6.20.15.
We see this on text tiles with body, but no title or subtitle.  Adding an empty title would make the tile too large for the dashboard.

**Comment by mjassows** [comment]
Although it only fails when it is attempting to overwrite an existing dashboard (using --force).  If I move the existing dashboard to trash and delete from trash, the import works without error.

**Comment by deangelo-llooker** [comment]
I just pushed gazer version 0.2.19. I believe that will fix this issue. If it does not fix we can reopen.
