### ISSUE TITLE
2nd attempt to overwrite dashboard with text element fails with "Result Maker IDs should not be provided for text elements"

### ISSUE THREAD

**Issue by sabarber-looker** [looker-open-source/gzr#42]
When attempting to overwrite a dashboard with a text element for the 2nd time, import fails with the following error:

```
Error updating dashboard_element(6,{
  "body_text": null,
  "dashboard_id": 8,
  "look_id": null,
  "merge_result_id": null,
  "note_display": null,
  "note_state": null,
  "note_text": null,
  "query_id": null,
  "refresh_interval": null,
  "result_maker": null,
  "subtitle_text": null,
  "title": null,
  "title_hidden": false,
  "title_text": "State Data",
  "type": "text"
})
Validation Failed
{:field=>"type", :code=>"invalid", :message=>"Result Maker IDs should not be provided for text elements", :documentation_url=>"http://docs.looker.com/"}

```

**Comment by sabarber-looker** [comment]
To reproduce this, I have to attempt to re-import multiple times.

1st attempt to import (with no existing dashboard):  SUCCESS
2nd attempt to import (with existing dashboard, using --force):  SUCCESS
3rd attempt to import (with existing dashboard, using --force):  FAIL as above

**Comment by sabarber-looker** [comment]
Debug output:

**Attempt 1:  SUCCESS**
_gzr dashboard import "Dashboard_3_State Dashboard.json" 13 --host=192.168.0.173 --no-verify-ssl --force --debug_

options: {"debug"=>true, "host"=>"192.168.0.173", "port"=>"19999", "ssl"=>true, "verify_ssl"=>false, "timeout"=>60, "force"=>true}
API 3.1 available? true
connecting to {:api_endpoint=>"https://192.168.0.173:19999/api/3.1", :connection_options=>{:ssl=>{:verify=>false}, :request=>{:timeout=>60}}, :user_agent=>"Gazer 0.2.14", :netrc=>true, :netrc_file=>"~/.netrc"}
check for connectivity: true
verify authentication: true
Modifying existing Look Average Age by State in space 13
Creating dashboard element {:body_text=>nil, :note_display=>nil, :note_state=>nil, :note_text=>nil, :refresh_interval=>nil, :subtitle_text=>nil, :title=>nil, :title_hidden=>false, :title_text=>nil, :type=>"vis", :result_maker=>{:id=>1, :dynamic_fields=>nil, :filterables=>[{:model=>"thelook", :view=>"inventory_items", :name=>nil, :listen=>[]}], :sorts=>["users.average_age desc"], :merge_result_id=>nil, :total=>nil, :query_id=>190, :query=>{:id=>190, :view=>"inventory_items", :fields=>["users.state", "users.average_age"], :pivots=>nil, :fill_fields=>nil, :filters=>nil, :filter_expression=>nil, :sorts=>["users.average_age desc"], :limit=>"500", :column_limit=>nil, :total=>nil, :row_total=>nil, :subtotals=>nil, :runtime=>0.033350000000000005, :vis_config=>{:type=>"looker_map"}, :filter_config=>{}, :visible_ui_sections=>nil, :slug=>"RTzRHDt", :dynamic_fields=>nil, :client_id=>"WFAIopA91qx33ghTbqnTqe", :share_url=>"https://localhost:9999/x/WFAIopA91qx33ghTbqnTqe", :expanded_share_url=>"https://localhost:9999/explore/thelook/inventory_items?fields=users.state,users.average_age&sorts=users.average_age+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22type%22%3A%22looker_map%22%7D&filter_config=%7B%7D&origin=share-expanded", :url=>"/explore/thelook/inventory_items?fields=users.state,users.average_age&sorts=users.average_age+desc&limit=500&query_timezone=America%2FLos_Angeles&vis=%7B%22type%22%3A%22looker_map%22%7D&filter_config=%7B%7D", :query_timezone=>"America/Los_Angeles", :has_table_calculations=>false, :model=>"thelook", :can=>{:run=>true, :see_results=>true, :explore=>true, :create=>true, :show=>true, :cost_estimate=>true, :index=>true, :see_lookml=>true, :see_derived_table_lookml=>true, :see_sql=>true, :generate_drill_links=>true, :download=>true}}, :vis_config=>{:type=>"looker_map"}}, :query_id=>nil, :look_id=>9, :merge_result_id=>nil}
Creating dashboard element {:body_text=>nil, :note_display=>nil, :note_state=>nil, :note_text=>nil, :refresh_interval=>nil, :subtitle_text=>nil, :title=>nil, :title_hidden=>false, :title_text=>"State Data", :type=>"text", :result_maker=>nil, :query_id=>nil, :look_id=>nil, :merge_result_id=>nil}
Updating dashboard layout 14
Updating dashboard layout component 12
Updating dashboard layout component 13
Imported dashboard 14
logout

**Attempt 2 -- SUCCESS but...**
_gzr dashboard import "Dashboard_3_State Dashboard.json" 13 --host=192.168.0.173 --no-verify-ssl --force --debug_

options: {"debug"=>true, "host"=>"192.168.0.173", "port"=>"19999", "ssl"=>true, "verify_ssl"=>false, "timeout"=>60, "force"=>true}
API 3.1 available? true
connecting to {:api_endpoint=>"https://192.168.0.173:19999/api/3.1", :connection_options=>{:ssl=>{:verify=>false}, :request=>{:timeout=>60}}, :user_agent=>"Gazer 0.2.14", :netrc=>true, :netrc_file=>"~/.netrc"}
check for connectivity: true
verify authentication: true
Modifying existing dashboard 14 State Dashboard in space 13
Modifying existing Look Average Age by State in space 13
Updating dashboard element 12
Updating dashboard element 13
Updating dashboard layout 14
Updating dashboard layout component 12
Updating dashboard layout component 13
Imported dashboard 14
logout

**Attempt 3:  FAIL**
_gzr dashboard import "Dashboard_3_State Dashboard.json" 13 --host=192.168.0.173 --no-verify-ssl --force --debug_

options: {"debug"=>true, "host"=>"192.168.0.173", "port"=>"19999", "ssl"=>true, "verify_ssl"=>false, "timeout"=>60, "force"=>true}
API 3.1 available? true
connecting to {:api_endpoint=>"https://192.168.0.173:19999/api/3.1", :connection_options=>{:ssl=>{:verify=>false}, :request=>{:timeout=>60}}, :user_agent=>"Gazer 0.2.14", :netrc=>true, :netrc_file=>"~/.netrc"}
check for connectivity: true
verify authentication: true
Modifying existing dashboard 14 State Dashboard in space 13
Modifying existing Look Average Age by State in space 13
Updating dashboard element 13
Updating dashboard element 12
Error updating dashboard_element(12,{
  "body_text": null,
  "dashboard_id": 14,
  "look_id": null,
  "merge_result_id": null,
  "note_display": null,
  "note_state": null,
  "note_text": null,
  "query_id": null,
  "refresh_interval": null,
  "result_maker": null,
  "subtitle_text": null,
  "title": null,
  "title_hidden": false,
  "title_text": "State Data",
  "type": "text"
})
Validation Failed
{:field=>"type", :code=>"invalid", :message=>"Result Maker IDs should not be provided for text elements", :documentation_url=>"http://docs.looker.com/"}
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/looker-sdk-0.0.6/lib/looker-sdk/response/raise_error.rb:15:in `on_complete'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/connection.rb:175:in `patch'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/looker-sdk-0.0.6/lib/looker-sdk/client.rb:280:in `request'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/looker-sdk-0.0.6/lib/looker-sdk/client.rb:108:in `patch'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/looker-sdk-0.0.6/lib/looker-sdk/client/dynamic.rb:99:in `invoke_remote'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/looker-sdk-0.0.6/lib/looker-sdk/client/dynamic.rb:63:in `method_missing'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/gazer-0.2.14/lib/gzr/modules/dashboard.rb:118:in `update_dashboard_element'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/gazer-0.2.14/lib/gzr/commands/dashboard/import.rb:195:in `sync_dashboard_element'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/gazer-0.2.14/lib/gzr/commands/dashboard/import.rb:75:in `block (3 levels) in execute'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/gazer-0.2.14/lib/gzr/command.rb:251:in `block in pairs'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/gazer-0.2.14/lib/gzr/command.rb:251:in `collect'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/gazer-0.2.14/lib/gzr/command.rb:251:in `pairs'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/gazer-0.2.14/lib/gzr/commands/dashboard/import.rb:74:in `block (2 levels) in execute'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/gazer-0.2.14/lib/gzr/modules/filehelper.rb:78:in `read_file'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/gazer-0.2.14/lib/gzr/commands/dashboard/import.rb:54:in `block in execute'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/gazer-0.2.14/lib/gzr/modules/session.rb:193:in `with_session'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/gazer-0.2.14/lib/gzr/commands/dashboard/import.rb:50:in `execute'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/gazer-0.2.14/lib/gzr/commands/dashboard.rb:58:in `import'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/Users/scott/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/gazer-0.2.14/exe/gzr:36:in `<top (required)>'
/Users/scott/.rbenv/versions/2.3.8/bin/gzr:22:in `load'
/Users/scott/.rbenv/versions/2.3.8/bin/gzr:22:in `<main>'
logout
ERROR: Validation Failed

**Comment by deangelo-llooker** [comment]
I just pushed gazer version 0.2.19. I believe that will fix this issue. If it does not fix we can reopen.
