### ISSUE TITLE
Error importing dashboards and looks to empty space

### ISSUE THREAD

**Issue by SSpencerDE** [looker-open-source/gzr#43]
I am trying to import my dashboards & looks to an empty space.  I deleted the contents from the space and the trash, so there shouldn't be no objects that already exist.  I get the error below.  I have updated Gazer to the latest and no change.  

Error updating dashboard_element(3265,{
  "body_text": null,
  "dashboard_id": null,
  "look_id": 1414,
  "merge_result_id": null,
  "note_display": null,
  "note_state": null,
  "note_text": null,
  "query_id": null,
  "refresh_interval": null,
  "result_maker": {
    "filterables": [
      {
        "model": "partner_engagement",
        "view": "tblassetclicklog",
        "name": null,
        "listen": [
          {
            "dashboard_filter_name": "Account Name",
            "field": "account.name_raw"
          },
          {
            "dashboard_filter_name": "School Name",
            "field": "site.name"
          },
          {
            "dashboard_filter_name": "School GUID",
            "field": "site.site_guid"
          },
          {
            "dashboard_filter_name": "Date",
            "field": "tblassetclicklog.click_date"
          }
        ]
      }
    ]
  },
  "subtitle_text": null,
  "title": null,
  "title_hidden": false,
  "title_text": null,
  "type": "vis"
})
Not found

**Comment by pioneer903** [comment]
Getting the same error after upgrading to 6.18. It was working in 6.10, though it was not able to update existing dashboards as reported in [issue 33](https://github.com/looker-open-source/gzr/issues/33)
$ ll
-rw-r--r--. 1 looker domain users 309539 Sep 18 09:53 Dashboard_1911_Current Security Posture.json
$ gzr dashboard import 'Dashboard_1911_Current Security Posture.json' 16 --host=s-looker.company.com --no-verify-ssl --force
Error creating dashboard({
  "description": null,
  "hidden": false,
  "query_timezone": null,
  "refresh_interval": "12 hours",
  "title": "Current Security Posture",
  "background_color": null,
  "load_configuration": "cache_run",
  "lookml_link_id": null,
  "show_filters_bar": null,
  "show_title": null,
  "text_tile_text_color": null,
  "tile_background_color": null,
  "tile_text_color": null,
  "title_color": null,
  "deleted": false,
  "slug": "xxxx",
  "space_id": "16",
  "user_id": 1377
})
Not found

ERROR: Not found

**Comment by pioneer903** [comment]
Thank you for the comment @ebar. I found two issues: 
1. I was using an older version of Gazer
2. My API account credentials were incorrect
Thanks to the Looker support team that helped me narrow it down quickly
