### ISSUE TITLE
Dashboards say they import fine, but I'm not seeing them in the folder.

### ISSUE THREAD

**Issue by lonza-ba** [looker-open-source/gzr#45]
Dashboards say they import fine, but I'm not seeing them in the folder.

**Comment by deangelo-llooker** [comment]
We are transitioning from using "spaces" to using "folders". The space_id field from the source json is ignored on import, since we are intentionally putting it into a different space, but the folder_id field was not ignored.

I recently pushed a new version which should resolve this.
