### ISSUE TITLE
"Error: Not found" when importing dashbaord

### ISSUE THREAD

**Issue by lonza-ba** [looker-open-source/gzr#46]
C:\Users\aolson>gzr dashboard import "C:\Users\aolson\Engineering & Facilities\Dashboard_48_Engineering & Facilities Detail.json" 193 --host=lonza.eu.looker.com --force
Error creating dashboard({
  "description": null,
  "hidden": false,
  "query_timezone": null,
  "refresh_interval": null,
  "title": "Engineering & Facilities Detail",
  "background_color": null,
  "load_configuration": "cache_run",
  "lookml_link_id": null,
  "show_filters_bar": null,
  "show_title": null,
  "text_tile_text_color": null,
  "tile_background_color": null,
  "tile_text_color": null,
  "title_color": null,
  "folder_id": 38,
  "deleted": false,
  "slug": "uo5bLXwHSFUbskkFeAidva",
  "space_id": "193",
  "user_id": 15
})
Not found

ERROR: Not found

**Comment by deangelo-llooker** [comment]
I need to do some rework to incorporate folders. I just pushed a new version that should at least ignore folders for the time being.

**Comment by HPNoha** [comment]
@lonza-ba I'm running into the same issue, would you please elaborate on how you fixed this issue?
