### ISSUE TITLE
Dashboard imports to random space

### ISSUE THREAD

**Issue by sam-pitcher** [looker-open-source/gzr#47]
I have been gazering dashboards from a test instance to a prod instance. When I imported a dashboard to update an existing one, it looked like the dashboard was deleted. Then when I ran the command again without --force, it became apparent that it was imported into the space I didn't specify. It imported it into space 25, whereas I stated 389.

In between 2 and 3 (below) is where it looked like the content was deleted.

dysonuk.eu.looker.com (6.22.11) and dysonprod.eu.looker.com (6.22.11)
gzr (v0.2.14)

`  1 $ gzr dashboard cat sjmMNV6XVODeUh1c2bsk6v --host=dysontest.eu.looker.com > global_overview.json

  2 $ gzr dashboard import global_overview.json 389 --host=dysonuk.eu.looker.com --force

  3 $ gzr dashboard import global_overview.json 389 --host=dysonuk.eu.looker.com
slug sjmMNV6XVODeUh1c2bsk6v already used for dashboard Global overview | Direct control tower in space 25
dashboard will be imported with new slug
Error creating dashboard({
  "description": null,
  "hidden": false,
  "query_timezone": "UTC",
  "refresh_interval": null,
  "title": "Global overview | Direct control tower",
  "background_color": null,
  "load_configuration": "cache_run",
  "lookml_link_id": "digital_direct::global_overview__direct_control_tower",
  "show_filters_bar": null,
  "show_title": null,
  "text_tile_text_color": null,
  "tile_background_color": null,
  "tile_text_color": null,
  "title_color": null,
  "folder_id": 25,
  "deleted": false,
  "space_id": "389",
  "user_id": 106
})
Validation Failed
{:field=>"[:title, :space_id]", :code=>"already_exists", :message=>"Dashboard with this title already exists.", :documentation_url=>"http://docs.looker.com/"}
ERROR: Validation Failed`

**Comment by deangelo-llooker** [comment]
If you update the version of gazer to the most recent, it **should** work. On import, I set the space_id with the destination space. But the folder_id is a relatively new field and comes along. When both are present, looker uses the folder_id instead of the space_id. Recent versions of gazer should fix this.
