### ISSUE TITLE
Gazer 0.2.14 - dashboard exported then imported across environments ends up in space with wrong id

### ISSUE THREAD

**Issue by jakebanks** [looker-open-source/gzr#50]
Hello,

We are hosting Looker 6.22.16 with on-prem clustered setups for each region. If I export a space from region A's environment with Gazer (lets say it has space id 123), then import it to space 456 in region B's environment with
`gzr dashboard import "MyDashboard.json" 456 --host example.com --port 443 --debug --force --no-verify-ssl`, 
this actually results in the dashboard being uploaded to space 123 in region B, not space 456. Note that space 123 already existed in region B's environment. 

I suspect `MyDashboard.json` having a reference to space 123 is part of the issue. 

I'm not sure if this is still an issue, because I haven't been able to test on 0.2.19 due to [this issue](https://github.com/looker-open-source/gzr/issues/49).

Thanks a lot.

**Comment by jakebanks** [comment]
I should say, modifying the space id referred to in `MyDashboard.json` didn't change its target.

**Comment by jakebanks** [comment]
As a workaround, I've been uploading the dashboards to the new environment into the space with the space id they came from, then moving them to the appropriate space. I hit a situation where the space ID doesn't exist in the new environment, and it threw this:
```
Error creating dashboard({
  "folder_id": 81,
  "space_id": "58"
})
```

Note that space id 58 is what I passed as an argument, but folder id 81 is the space they were downloaded from.

Thanks

**Comment by deangelo-llooker** [comment]
The latest versions of gzr remove the conflicting folder_id. The attributes folder_id and space_id are synonyms. We basically decided to rename the attribute. But when both are provided looker uses the folder_id rather than the space_id.

**Comment by jakebanks** [comment]
Thanks @deangelo-llooker
