### ISSUE TITLE
All the titles for Dashboard Tiles are missing

### ISSUE THREAD

**Issue by lonza-ba** [looker-open-source/gzr#52]
All of the titles for dashboard tiles are missing when I move a dashboard over.  I can see the titles in the export files, so it has something to do with the import.

**Comment by deangelo-llooker** [comment]
I believe this is a side effect of https://github.com/looker-open-source/gzr/issues/51. The title was coming from the Look title. Please retest with version 0.2.21.

If I'm wrong would you please send me the dashboard file that you import, and then export the target dashboard and send me that file as well. It will help my investigation.

I'm closing this for now, but we can reopen if you still see the problem.
