### ISSUE TITLE
Looker ruby sdk is sending api key and secret via querystring

### ISSUE THREAD

**Issue by yingbiao** [looker-open-source/gzr#57]
I submitted an issue to looker-sdk-ruby (https://github.com/looker/looker-sdk-ruby/issues/87), because it sends api key and secret via querystring, it should be via body. 

Once that is fixed, gzr should update the looker ruby sdk version.

**Comment by drstrangelooker** [comment]
Thanks. I'll track.

**Comment by drstrangelooker** [comment]
I have a pull request to https://github.com/looker/looker-sdk-ruby/pull/89 to fix this. Once that is handled I'll update my code. They just accepted my prior patch so once they accept this and publish I'll also be able to remove my monkey patch as well.

**Comment by drstrangelooker** [comment]
This should be fixed. We can reopen if it isn't.
