### ISSUE TITLE
Dashboard Import Fails - Result Maker IDs should not be provided Error Msg

### ISSUE THREAD

**Issue by Dave0404** [looker-open-source/gzr#58]
When migrating content from one instance to another instance we get the below error when trying to import a dashboard. "Result Maker IDs should not be provided for text elements", :documentation_url=>"http://docs.looker.com/". We get this message regardless of whether it is a new import or an overwrite (force). We are leveraging the space export feature to get the json files for import.

This may be similar to https://github.com/looker-open-source/gzr/issues/40 but have not yet been able to resolve based on comments from that issue.

gzr version - v0.2.32
Looker version - 6.24.30

Full Error Text:
Error updating dashboard_element(77,{
  "body_text": null,
  "dashboard_id": 10,
  "look_id": null,
  "merge_result_id": null,
  "note_display": null,
  "note_state": null,
  "note_text": null,
  "query_id": null,
  "refresh_interval": null,
  "result_maker": null,
  "subtitle_text": "",
  "title": null,
  "title_hidden": false,
  "title_text": "Title",
  "type": "text"
})
Validation Failed
{:field=>"type", :code=>"invalid", :message=>"Result Maker IDs should not be provided for text elements", :documentation_url=>"http://docs.looker.com/"}

**Comment by Dave0404** [comment]
Was able to find a workaround that entails deleting it both from the space and from the trash. Would still be great to figure out what is causing it so we don't have to do that process everytime for the offending dashboards.

**Comment by pioneer903** [comment]
Wanted to add more details. In our case, it works for the initial dashboard import. We are getting this error only when updating a dashboard that had a tile removed. Tested it with text and query tiles and got the same error message. Looker 6.24.35, Gazer v0.2.32

**Comment by drstrangelooker** [comment]
We can't update a non-text dashboard element to a text dashboard element. This latest release deletes and creates a new element.

**Comment by pioneer903** [comment]
We are not updating elements. It happens when an element is deleted. For example, if i had a dashboard with two elements and deployed it once, it works fine. Then if i remove one element from the source instance and try to deploy again, that is when i get the error. Hope that helps

**Comment by alixlelli** [comment]
@drstrangelooker ^^ let us know if you need more info on the above example! Thanks!
