### ISSUE TITLE
Users migration

### ISSUE THREAD

**Issue by AlexeyV-Turner** [looker-open-source/gzr#6]
It's not an issue but rather functionality request
If it possible to export all the Looker users from one instance and import them back to another one.
It could be potentially user_id clash between the instances, but it's fine for me to fix it manually.

**Comment by deangelo-llooker** [comment]
I'll research this. Thanks

**Comment by bryanconlon** [comment]
Was curious about this feature request.  Any chance to look at adding this feature of exporting users?  Thanks.

**Comment by michaelcramer** [comment]
Noted enhancement suggestion for potential addition to roadmap.
