### ISSUE TITLE
Dashboard Import Fails - Result Maker IDs should not be provided continued

### ISSUE THREAD

**Issue by Dave0404** [looker-open-source/gzr#61]
This is similar to https://github.com/looker-open-source/gzr/issues/58 (#58) but now appears to occur as a result of URL element within a textbox.

Modifying existing dashboard 125 PAGE 4 - PERFORMANCE in space 17
Error updating dashboard_element(1400,{
  "body_text": "<img src=\"https://resources.s3.awsregion.amazonaws.com/logos/icon.png\" width=\"200\">",
  "dashboard_id": 125,
  "look_id": null,
  "merge_result_id": null,
  "note_display": null,
  "note_state": null,
  "note_text": null,
  "query_id": null,
  "refresh_interval": null,
  "result_maker": null,
  "subtitle_text": null,
  "title": null,
  "title_hidden": false,
  "title_text": null,
  "type": "text"
})
Validation Failed
{:field=>"type", :code=>"invalid", :message=>"Result Maker IDs should not be provided for text elements", :documentation_url=>"http://docs.looker.com/"}

Gazer - 0.2.35
Looker - 7.0.19

**Comment by ajcrutch** [comment]
Spoke with @Dave0404 and wanted to add additional context.  They are able to workaround this by first deleting all elements in the target (to-be-updated) dashboard before using gazer to load changes into that target dashboard.  What is extra strange is that sometimes those same tiles which are giving errors exist in other dashboard which do not exhibit this problem.  Current workaround is to do updates this way and do so during off hours.
