### ISSUE TITLE
Query ID, Look ID, and Merge Result ID should not be specified if a Result Maker ID is provided

### ISSUE THREAD

**Issue by amysouthwood** [looker-open-source/gzr#62]
v0.2.36
looker 7.4.16

When trying to import dashboard into the target instance I get the following error. The error occurs when the dashboard is being moved over for the first time as well as when the dashboard is being replaced. Workaround was to edit the json file and delete all of the "result_maker_id": 5941, lines that were showing in the error messages.

Error creating dashboard_element({
  "body_text": null,
  "note_display": null,
  "note_state": null,
  "note_text": null,
  "refresh_interval": null,
  "result_maker_id": 5941,
  "subtitle_text": null,
  "title": "Channel performance YTD",
  "title_hidden": false,
  "title_text": null,
  "type": "vis",
  "result_maker": {
    "filterables": [
      {
        "model": "digital_direct",
        "view": "sap_sales_reporting_data",
        "name": null,
        "listen": [
          {
            "dashboard_filter_name": "Channel",
            "field": "sap_sales_reporting_data.channel"
          },
          {
            "dashboard_filter_name": "Product Category",
            "field": "sap_sales_reporting_data.product_category_grouped"
          },
          {
            "dashboard_filter_name": "Month Displayed",
            "field": "parameters.current_previous_month_select"
          },
          {
            "dashboard_filter_name": "Country",
            "field": "marketmaster.market_country"
          }
        ]
      }
    ]
  },
  "query_id": 173016,
  "look_id": null,
  "merge_result_id": null,
  "dashboard_id": 313
})
Validation Failed
{:field=>"query_id", :code=>"invalid", :message=>"Query ID must not have a value if a Look ID or Merge Result ID is provided", :documentation_url=>"http://docs.looker.com/"}{:field=>"look_id", :code=>"invalid", :message=>"Look ID must not have a value if a Query ID or Merge Result ID is provided", :documentation_url=>"http://docs.looker.com/"}{:field=>"merge_result_id", :code=>"invalid", :message=>"Merge result ID must not have a value if Look ID or Query ID is provided.", :documentation_url=>"http://docs.looker.com/"}{:field=>"result_maker_id", :code=>"invalid", :message=>"Query ID, Look ID, and Merge Result ID should not be specified if a Result Maker ID is provided.", :documentation_url=>"http://docs.looker.com/"}

**Comment by amysouthwood** [comment]
Also to note, gazer only had this error when moving the dashboard to a certain instance (target). The target instance that it failed on had the dashboard gazered to it at an early point in time potentially on an older gazer version but I am not sure. There were no issues when gazering the dashboard between folders on the source instance or gazering it to an entirely different instance.

**Comment by andrew-vts** [comment]
We're seeing this also. It appears that the Looker API now considers a `null` value to be present.

**Comment by samadhusain** [comment]
We're having the same issue when moving content between our dev and test instances. Has this been fixed?
