### ISSUE TITLE
Dashboard errors with --force

### ISSUE THREAD

**Issue by amysouthwood** [looker-open-source/gzr#63]
v0.2.36
looker 7.4.16

For one dashboard if I try to replace it with --force I get the following error. I can bring the dashboard over via gazer for the first time with out error but when I try to replace the existing it errors. Workaround is to delete existing dashboard and empty trash then import the new dashboards. This results in a longer downtime.

```Error updating dashboard_layout(12,{
  "type": "newspaper",
  "active": true,
  "column_width": null,
  "width": null
})
An error has occurred.

```

**Comment by JakubDvorakFD** [comment]
I am having the same issue

`Modifying existing dashboard 412 Leads Dashboard in space 141
Error updating dashboard(412,{
  "description": null,
  "hidden": false,
  "query_timezone": null,
  "refresh_interval": null,
  "title": "Leads Dashboard",
  "background_color": null,
  "crossfilter_enabled": false,
  "load_configuration": "cache_run",
  "lookml_link_id": null,
  "show_filters_bar": null,
  "show_title": null,
  "text_tile_text_color": null,
  "tile_background_color": null,
  "tile_text_color": null,
  "title_color": null,
  "preferred_viewer": null,
  "deleted": false,
  "folder_id": 235,
  "appearance": null
})
Validation Failed
{:field=>"[:title, :space_id]", :code=>"already_exists", :message=>"Dashboard with this title already exists.", :documentation_url=>"http://docs.looker.com/"}
ERROR: Validation Failed`

**Comment by msswanson** [comment]
I also noticed this issue while doing a deploy the other day. 

One other thing I noticed at the same time is that the space ID in my command was not passed through to my Prod instance, instead the dashboard partially imported under the same space ID as it was in in my dev instance, which was a user's space...very odd...
