### ISSUE TITLE
Connection errors with --no-verify-ssl option for Gazer v0.2.36

### ISSUE THREAD

**Issue by biswanath-palo** [looker-open-source/gzr#64]
gzr returns the connection error with --no-verify-ssl option is specified.

ERROR: Connection Failed.
Did you specify the --no-ssl option for an ssl secured server?

**Comment by jcarah** [comment]
I believe that this is the generic failure message, and can often not be related at all to anything ssl. Paste a command that you're attempting, and we can help debug.

**Comment by v360-eduardo-marques** [comment]
facing the same problem here

the command I'm trying is:
gzr dashboard cat 1 --host meuvarejo360.cloud.looker.com --client_id <id> --client_secret <secret>

**Comment by v360-eduardo-marques** [comment]
tried putting the access config on ~/.netrc but the problem persists

is there a way to troubleshoot this?

**Comment by MartinGuindon** [comment]
@biswanath-palo Are you on a GCP instance (*.cloud.looker.com), by any chance?

I'm able to replicate the issue on a GCP-hosted instance, but its working fine on an AWS-hosted instance.

**Comment by v360-eduardo-marques** [comment]
yes, I'm on a GCP instance

**Comment by MartinGuindon** [comment]
I've confirmed the issue on a 2nd GCP-hosted instance... so definitely look like to be a compatibility issue with the new GCP instances.

@drstrangelooker fyi.

**Comment by MartinGuindon** [comment]
Found a fix. GCP instances clients need to add the following to the command line, because the API listens on a different port than AWS instances.

`--port 443`

**Comment by drstrangelooker** [comment]
I'm going to add this not only to the README but also to the error message.
