### ISSUE TITLE
gzr space ls fields option gives incorrect results

### ISSUE THREAD

**Issue by JackDavidson** [looker-open-source/gzr#65]
This is the command I am running with gazer 0.2.38:

```
gzr space ls "Test Parent" --host ${SOURCE_HOST} --fields id,name
+--+----+
|id|name|
+--+----+
|  |15  |Test Parent|||||
|15|41  |Child 1|||||
|15|38  |Child 2|||||
|15|256 |Child 3|||||
|15|39  |Child 4|||||
|15|40  |Child 5|||||
|15|42  |Child 6|||||
+--+----+
```

As you can see, the formatting is not correct. Also, the parent_id field is included even when its not in the list of the --fields. The --fields option seems to have worked for the first line only.

**Comment by drstrangelooker** [comment]
Fixes in v0.2.40
