### ISSUE TITLE
Error creating query - cross referencing between 2 models with applied access grants

### ISSUE THREAD

**Issue by smani2508** [looker-open-source/gzr#66]
Hi Team,

In an attempt to push a dashboard containing elements referencing across models (where one of the models has the access grant in place while the other does not) with applied access_grants gave us an error message: 

Error creating query({
  "view": "example_view",
  "fields": [
    "example_view.field1_name",
    "example_view.field2_name"
  ],
  "pivots": null,
  "fill_fields": [
    "example_view.field2_name"
  ],
  "filters": {
    "example_view.date": "8 weeks ago for 8 weeks",
    "example_view.timeframe_picker": "Weekly"
  },
  "filter_expression": null,
  "sorts": [
    "example_view.field2_name"
  ],
  "limit": "7",
  "column_limit": "50",
  "total": null,
  "row_total": null,
  "subtotals": null,
  "runtime": 4.976660966873169,
  "vis_config": {
    "x_axis_gridlines": false,
    "y_axis_gridlines": false,
    "show_view_names": false,
    "y_axes": [
      {
        "label": "",
        "orientation": "left",
        "series": [
          {
            "axisId": "example_view.field1_name",
            "id": "example_view.field1_name",
            "name": "Field 1"
          }
        ],
        "showLabels": false,
        "showValues": true,
        "maxValue": 30,
        "valueFormat": "$##",
        "unpinAxis": false,
        "tickDensity": "default",
        "type": "linear"
      },
      {
        "label": "",
        "orientation": "right",
        "series": [
          {
            "axisId": "sos_change",
            "id": "sos_change",
            "name": "SoS % Change"
          }
        ],
        "showLabels": false,
        "showValues": false,
        "maxValue": 1.4,
        "unpinAxis": false,
        "tickDensity": "default",
        "type": "linear"
      }
    ],
    "show_y_axis_labels": true,
    "show_y_axis_ticks": true,
    "y_axis_tick_density": "default",
    "y_axis_tick_density_custom": 5,
    "show_x_axis_label": false,
    "show_x_axis_ticks": true,
    "y_axis_scale_mode": "linear",
    "x_axis_reversed": false,
    "y_axis_reversed": false,
    "plot_size_by_field": false,
    "trellis": "",
    "stacking": "",
    "limit_displayed_rows": true,
    "limit_displayed_rows_values": {
      "show_hide": "hide",
      "first_last": "first",
      "num_rows": "1"
    },
    "legend_position": "center",
    "series_types": {
      "change_from_prev_month": "line",
      "sos_change": "line"
    },
    "point_style": "circle_outline",
    "series_colors": {
      "example_view.field1_name": "#E8DBE1",
      "change_from_prev_month": "#C4069A"
    },
    "show_value_labels": true,
    "label_density": 25,
    "label_color": [
      "#693C57",
      "#C4069A"
    ],
    "x_axis_scale": "auto",
    "y_axis_combined": true,
    "ordering": "none",
    "show_null_labels": false,
    "show_totals_labels": false,
    "show_silhouette": false,
    "totals_color": "#808080",
    "custom_color_enabled": true,
    "show_single_value_title": true,
    "show_comparison": false,
    "comparison_type": "change",
    "comparison_reverse_colors": true,
    "show_comparison_label": true,
    "enable_conditional_formatting": false,
    "conditional_formatting_include_totals": false,
    "conditional_formatting_include_nulls": false,
    "type": "looker_column",
    "hidden_fields": [
      "end_date_of_week",
      "example_view.field2_name"
    ]
  },
  "filter_config": {
    "example_view.date": [
      {
        "type": "past",
        "values": [
          {
            "constant": "8",
            "unit": "c_wk"
          }
        ],
        "id": 1,
        "error": false
      }
    ],
    "example_view.timeframe_picker": [
      {
        "type": "is",
        "values": [
          {
            "constant": "Weekly"
          },
          {
          }
        ],
        "id": 2,
        "error": false
      }
    ]
  },
  "visible_ui_sections": null,
  "dynamic_fields": "[{\"table_calculation\":\"sos_change\",\"label\":\"SoS % Change\",\"expression\":\"(${example_view.field1_name})/(offset(${.example_view.field1_name},-1))-1\",\"value_format\":null,\"value_format_name\":\"percent_1\",\"_kind_hint\":\"measure\",\"_type_hint\":\"number\"},{\"table_calculation\":\"end_date_of_week\",\"label\":\"End Date of Week\",\"expression\":\"add_days(6,${example_view.field2_name})\",\"value_format\":null,\"value_format_name\":null,\"_kind_hint\":\"dimension\",\"_type_hint\":\"date\"},{\"table_calculation\":\"week\",\"label\":\"Week\",\"expression\":\"concat(extract_months(${now_media_acq_spend_subs.DT_week}),\\\"/\\\",extract_days(${example_view.field2_name}),\\\"-\\\",extract_months(${end_date_of_week}),\\\"/\\\",extract_days(${end_date_of_week}))\",\"value_format\":null,\"value_format_name\":null,\"_kind_hint\":\"dimension\",\"_type_hint\":\"string\"}]",
  "query_timezone": "UTC",
  "model": "MODEL_WITH_ACCESS_GRANT"
})
Not found

Is this a known issue?
The dashboard fails to deploy until the access grant code is commented entirely.

**Comment by drstrangelooker** [comment]
Can you tell me exactly what code you needed to comment out to make the deploy work?

**Comment by smani2508** [comment]
We are no longer seeing this issue. The user API that was being used for migration did not have access to the model/explores. Therefore, we were seeing the issue.
