### ISSUE TITLE
Provide soft vs hard delete controls on dashboards and looks

### ISSUE THREAD

**Issue by brettguenther** [looker-open-source/gzr#7]
Looker's sdk supports hard deletes, but soft deletes require a patch to the objects. Control over this behavior would be helpful.

See example patch here:

https://github.com/llooker/python_api_samples/blob/master/soft_delete_content.py

**Comment by deangelo-llooker** [comment]
implemented a `--soft` to soft delete and a `--restore` flag to un-soft delete in v0.2.25.
