### ISSUE TITLE
Importing a Look with a filter only date field with a date range specified, the imported look doesn't have the filters applied

### ISSUE THREAD

**Issue by LukaFontanilla** [looker-open-source/gzr#70]
When using Gazer to import a look with a filter-only date field specifying a range, the look's date filter shows blank in the UI in the importing instance (despite the correct where clause sql being generated). 

We would expect that like normal date filters, when importing content via gazer that the content maintains the original filter values.

Filters show when first viewing the imported look:
<img width="981" alt="Screen Shot 2020-06-23 at 12 57 22 PM" src="https://user-images.githubusercontent.com/51471651/85453950-41415300-b551-11ea-9e08-07f367bb0698.png">

Opening up the imported look's filter panel shows no filter values inputted:
<img width="978" alt="Screen Shot 2020-06-23 at 12 57 44 PM" src="https://user-images.githubusercontent.com/51471651/85453894-325aa080-b551-11ea-8c3f-829aa76a5f71.png">

**Comment by drstrangelooker** [comment]
Are you still seeing this? Can you send me the json file that you imported and then also cat the object after import and send me that json file?

If you don't want to send the whole file, you can diff the files and send me the relevant difference. The ids and urls of the objects will be different but that doesn't matter. Just look for the differences that describe the filters.
