### ISSUE TITLE
--dir creates crazy file names

### ISSUE THREAD

**Issue by daniel-nelson-looker** [looker-open-source/gzr#73]
Can the file names please be set in a flag instead of hardcoded? Dashboard names will sometimes include white spaces, emojis, and all kinds of other stuff that should not be in file names. 

examples:
Dashboard_6025_⭐\ DCL\ KPIs\ \(monthly\).json 
Dashboard_451_2020 Pulse.json

**Comment by drstrangelooker** [comment]
how about a flag like `--simple-file-names` that just does `Dashboard_<id number>.json` and `Look_<id number>.json`?
