### ISSUE TITLE
 Filters are not sent in merge results

### ISSUE THREAD

**Issue by bryanrubc** [looker-open-source/gzr#75]
When i tried to send a dasboard to PROD enviroment i saw that filters are not applied to merge results.

Could you help me?

I use gzr import command

**Comment by drstrangelooker** [comment]
If you use `gzr dashboard cat` to get the json file for the dashboard in production, you can diff that against the dashboard file that you imported. A bunch of things will be different, particularly the ids for all the components and the urls. But you should also see the filter settings. If you can post the missing filter settings (sanitize the values if they are sensitive) and post them here I should be able to fix.

**Comment by bryanrubc** [comment]
I just had to update the Gazer version and the problem disappeared

Thx
