### ISSUE TITLE
Gazer version 0.2.20 Issues

### ISSUE THREAD

**Issue by vmgponly** [looker-open-source/gzr#76]
I am getting below errors intermittently while executing gzr look import command in loop for gzr version 0.2.20. Please let me know if there is any solution for these errors.

1. ERROR: Nginx 502 Bad Gateway

2. 502 Server Error.Server Error.The server encountered a temporary error and could not complete your request. Please try again in 30 seconds.

3. /usr/local/share/gems/gems/gazer-0.2.20/lib/gzr/modules/look.rb:108:in `upsert_look': undefined method `fetch' for #<String:0x000055ff50675bb0> (NoMethodError)
	from /usr/local/share/gems/gems/gazer-0.2.20/lib/gzr/commands/look/import.rb:52:in `block (2 levels) in execute'
	
4. /usr/local/share/gems/gems/looker-sdk-0.0.7/lib/looker-sdk/client/dynamic.rb:105:in `method_missing': undefined method `me' for #<LookerSDK::Client:0x0000562c47743cd0> (NoMethodError)

**Comment by drstrangelooker** [comment]
This is a network error between you and the server. Nothing I can do.
