### ISSUE TITLE
gem install gazer gives an error

### ISSUE THREAD

**Issue by oldfaust** [looker-open-source/gzr#81]
ERROR:  While executing gem ... (Gem::DependencyError)
Unable to resolve dependencies: tty-table requires equatable (~> 0.5.0)

Any ideas?

**Comment by michaelcramer** [comment]
@oldfaust is this still an issue?  If so, could you please reply with the version of Ruby you're using?  Thanks!

**Comment by oldfaust** [comment]
Tried it on my mac now and it worked. Unfortunately don't remember the environment which was giving the error...
