### ISSUE TITLE
Cannot export Embed User and Unpublished reports using gzr ( `initialize': pathname contains null byte (ArgumentError) )

### ISSUE THREAD

**Issue by sheldon-sonar** [looker-open-source/gzr#85]
I cannot export Embed User and Unpublished reports using gzr.  I am trying export items in spaces 3 and 4.

Command:
gzr space export 3 --host sonarsoftwarestaging.looker.com --tgz sonarsoftwarestaging_export_20210311_2.tar.gz

Traceback (most recent call last):
        21: from /usr/local/bin/gzr:23:in `<main>'
        20: from /usr/local/bin/gzr:23:in `load'
        19: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/exe/gzr:36:in `<top (required)>'
        18: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        17: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        16: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        15: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        14: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
        13: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
        12: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        11: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        10: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         9: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/lib/gzr/commands/space.rb:80:in `export'
         8: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/lib/gzr/commands/space/export.rb:49:in `execute'
         7: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/lib/gzr/modules/session.rb:207:in `with_session'
         6: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/lib/gzr/commands/space/export.rb:58:in `block in execute'
         5: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/lib/gzr/commands/space/export.rb:137:in `process_space'
         4: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/lib/gzr/commands/space/export.rb:137:in `each'
         3: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/lib/gzr/commands/space/export.rb:138:in `block in process_space'
         2: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/lib/gzr/commands/space/export.rb:90:in `process_space'
         1: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/lib/gzr/commands/space/export.rb:90:in `new'
/var/lib/gems/2.5.0/gems/gazer-0.2.43/lib/gzr/commands/space/export.rb:90:in `initialize': pathname contains null byte (ArgumentError)

**Comment by jannarobertson-bytecode** [comment]
@sheldon-sonar as this issue is very outdated and we haven't heard back, we are closing it out. Please open another issue if you are still having difficulty with this or anything else; please include the Looker and Gazer/Ruby versions you're using. Thank you!
