### ISSUE TITLE
Cannot Import New Looks or Look-Linked Dashboards 

### ISSUE THREAD

**Issue by jordan-NMDP** [looker-open-source/gzr#86]
Migrating new looks or changing the name of existing looks causes the import to fail. Updating existing look-linked dashboards works as long as the name of the looks are not updated. This issue began with upgrade to Looker 21.4. The issue occurs on both dashboards and dashboards-next as well as individual looks. 

Looker Version: 21.4
Gazer Version: 0.2.44

Command: gzr dashboard import "C:\Users\jhemblin\Looker_Migrations\Dashboard_113.json" 412 --host looker.bethematch.org --client-id #### --client-secret #### --force

Error:
```
Modifying existing dashboard 593 Case Management Workload in space 412
Modifying existing Look 1795 Requests by Week * in space 412
Modifying existing Look 1796 Requests by Day of Week (Last 30 Days) in space 412
Modifying existing Look 1797 Prelims by Day of Week in space 412
Modifying existing Look 1798 Formals by Day of Week in space 412
Modifying existing Look 1799 Donor CT Requests by Day of Week in space 412
The color_collection(c54e61ca-19df-49fa-b8c7-30ad38912792) is not found
Error creating look({
  "title": "Collections & Shipments by Day of Week ~~",
  "description": null,
  "is_run_on_load": true,
  "deleted": false,
  "public": null,
  "slug": null,
  "query_id": 335925,
  "user_id": 439,
  "space_id": "412"
})
An error has occurred.

**Comment by jordan-NMDP** [comment]
@michaelcramer  this issue has been resolved, thanks.

**Comment by chaitanyavarman** [comment]
> @jordan-NMDP is this still an issue? If so, could you please respond with the version of Looker you're currently on? Thanks!

@michaelcramer we are same issue from two days, our looker version is 22.4.29

**Comment by chaitanyavarman** [comment]
> > @jordan-NMDP is this still an issue? If so, could you please respond with the version of Looker you're currently on? Thanks!
> 
> @michaelcramer we are facing same issue from two days, our looker version is 22.4.29

**Comment by jordan-NMDP** [comment]
@chaitanyavarman  this is no longer an issue. We were able to resolve it by turning off one of the lab features in Looker. I can't recall which lab feature it was though.

**Comment by chaitanyavarman** [comment]
> @chaitanyavarman this is no longer an issue. We were able to resolve it by turning off one of the lab features in Looker. I can't recall which lab feature it was though.

@jordan-NMDP let me check

**Comment by chaitanyavarman** [comment]
@jordan-NMDP thank you for quick reply but i am not able to find which lab feature to turn off,if you can recall please let us know
