### ISSUE TITLE
unable to import looks from dev to stg and stg to prod environments through gazer scirpt.

### ISSUE THREAD

**Issue by tamalampudi** [looker-open-source/gzr#88]
unable to import looks from dev to stg and stg to prod environments through gazer script. it was fine till we upgrade all instances to 21.4 , after upgrade only gazer script is working strangely, especially we are not able to migrate looks. getting below error:

Error creating look({
  "title": "Yield Lift / Drag PA CUST Level Last 4 Rolling Weeks",
  "description": null,
  "is_run_on_load": true,
  "deleted": false,
  "public": false,
  "slug": null,
  "query_id": 2485028,
  "user_id": 2,
  "space_id": "3806"
})
An error has occurred.

ERROR: An error has occurred.

**Comment by tamalampudi** [comment]
Hi ,
What we observed , once we upgrade the version from 21.4.17 to 21.4.25 gazer script stop working for looks migration but dashboards can able to migrate. getting the below error:

**Comment by tamalampudi** [comment]
error : 
(base) xxxx.xxxxxx@xxxxx Finance General % gzr look import 'Look_811_Yield Lift ∕ Drag PA CUST Level Last 4 Rolling Weeks.json' 3806 --host='xxxxxxxxxxxx.cloud.looker.com' --port='443' --client-id='xxxxxxxxxxx' --client-secret='xxxxxxxxxxxxxxx' --force
Error creating look({
  "title": "Yield Lift / Drag PA CUST Level Last 4 Rolling Weeks",
  "description": null,
  "is_run_on_load": true,
  "deleted": false,
  "public": false,
  "slug": null,
  "query_id": 2485028,
  "user_id": 2,
  "space_id": "3806"
})
An error has occurred.

**Comment by tamalampudi** [comment]
error : 
(base) xxxx.xxxxxx@xxxxx Finance General % gzr look import 'Look_811_Yield Lift ∕ Drag PA CUST Level Last 4 Rolling Weeks.json' 3806 --host='xxxxxxxxxxxx.cloud.looker.com' --port='443' --client-id='xxxxxxxxxxx' --client-secret='xxxxxxxxxxxxxxx' --force
Error creating look({
  "title": "Yield Lift / Drag PA CUST Level Last 4 Rolling Weeks",
  "description": null,
  "is_run_on_load": true,
  "deleted": false,
  "public": false,
  "slug": null,
  "query_id": 2485028,
  "user_id": 2,
  "space_id": "3806"
})
An error has occurred.

**Comment by bruce-nmdp** [comment]
experiencing the same error

**Comment by tamalampudi** [comment]
Once we disable the "Search Service" option under Labs, gazer script is working.. in 21.4.xx , we already tested it and raised a case with looker.

**Comment by jannarobertson-bytecode** [comment]
@tamalampudi as this issue is very outdated and we haven't heard back, we are closing it out. Please open another issue if you are still having difficulty with this or anything else; please include the Looker and Gazer/Ruby versions you're using. Thank you!
