### ISSUE TITLE
login: undefined method supported version

### ISSUE THREAD

**Issue by mehrmay** [looker-open-source/gzr#90]
Hi, 

I just installed the gzr utility along with other pre-reqs. I have setup the .netrc as well. I am getting following error when I run following command. Please help on how to solve it. 

gzr user me --host=hidden.cloud.looker.com --port=443 --no-ssl --debug

{"debug"=>true, "host"=>"hidden.cloud.looker.com", "port"=>"443", "ssl"=>false, "verify_ssl"=>false, "timeout"=>60, "force"=>false, "fields"=>"id,name,user_count,contains_current_user,externally_managed,external_group_id", "plain"=>false, "csv"=>false}
logout
Traceback (most recent call last):
	15: from /usr/local/bin/gzr:23:in `<main>'
	14: from /usr/local/bin/gzr:23:in `load'
	13: from /Library/Ruby/Gems/2.6.0/gems/gazer-0.2.44/exe/gzr:36:in `<top (required)>'
	12: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	11: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	10: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 9: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 8: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	 7: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	 6: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 5: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 4: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 3: from /Library/Ruby/Gems/2.6.0/gems/gazer-0.2.44/lib/gzr/commands/group.rb:82:in `ls'
	 2: from /Library/Ruby/Gems/2.6.0/gems/gazer-0.2.44/lib/gzr/commands/group/ls.rb:40:in `execute'
	 1: from /Library/Ruby/Gems/2.6.0/gems/gazer-0.2.44/lib/gzr/modules/session.rb:206:in `with_session'
**/Library/Ruby/Gems/2.6.0/gems/gazer-0.2.44/lib/gzr/modules/session.rb:122:in `login': undefined method `supported_versions' for #<String:0x00007fb1e316c410> (NoMethodError)**

**Comment by michaelcramer** [comment]
@mehrmay is this still an issue you're able to reproduce?  If so, could you please respond with the Looker version you're on?  Thanks!

**Comment by ddaugherty** [comment]
Hello @mehrmay, 

If you are still having issues with your configuration, please reply to this message, otherwise the issue will be marked closed in about 3 days.  

Thank you.
