### ISSUE TITLE
User content to run on a different project config 

### ISSUE THREAD

**Issue by sirmujahedin** [looker-open-source/gzr#92]
We have this scenario. 
We are trying to build a new looker project that is using a new db connection but with the same lookml contents like in the existing project. We can manage to duplicate the lookml contents but we are now facing the problem of redirecting all saved contents of some users (a certain department) to run on the new project with its new connection. 

Basically, we need a way to keep the existing user folders/subfolders structure with their contents of looks, dashboards and scheduled plans/jobs and just redirect them to use the new project. It can be done with gzr ? Can we update the project name and model names to the new project and new lookml .model files ? (new model file naming is required for the new project)
Thank you ! 
Dan

**Comment by drstrangelooker** [comment]
Yes, if you export a saved look or dashboard, modify the model names in the json, and then re-import it to the same place it should accomplish exactly what you need. That assumes that the new model consists of the explores with the same names and the same fields.

**Comment by sirmujahedin** [comment]
Thank you @drstrangelooker! That's great!
