### ISSUE TITLE
Pool calls from Gazer/Optimize Number of Connections

### ISSUE THREAD

**Issue by eric-lyons** [looker-open-source/gzr#93]
We use a [GCP NAT](https://cloud.google.com/nat/docs/ports-and-addresses#ports-reuse-tcp) Gzr fires off hundreds of API calls in a very short span of time. While none of the API calls overlap, there are definitely periods of 120 seconds where >~130 requests will fire. With our limit of 128 source ports, they are needing to be reused while within that 120 second window before they can be reused based on the cloud NAT limitations.  When we make a request on a shared space the number of requests calls the functionality to fail. If this could be packaged or streamlined (e.g. eliminate the repeated calls to collor_collections) this would solve our issue.

**Comment by drstrangelooker** [comment]
Thanks for the pull request
