### ISSUE TITLE
Command 'role rm ROLE_ID' Does Not Work

### ISSUE THREAD

**Issue by tkofford-bytecode** [looker-open-source/gzr#95]
The gazer command 'gzr role rm ROLE_ID' does not remove or delete the role given by ROLE_ID. Looking at the source for the remove role command, it appears that there's a copy/paste error. A variable "role_id" is passed in, but method "delete_role()" is called with an undefined variable "delete_role(@plan_id)", so no role is ever deleted. Changing that call to "delete_role(@plan_id)" which correctly uses the role_id parameter passed in resolves the issue.

Automated tests also do not catch this as the ruby looker SDK does not return an error when an undefined role id is passed into the delete role API call, but instead returns normally (i.e., no exceptions).

**Comment by drstrangelooker** [comment]
fixed
